function poincareRR_tabelapct(main_window,Y)

h=figure(main_window+1);
clf,

%janela=[590 390 435 320];
janela=[150  140   650   570];

set(h,'position',janela,'name','ECGLAB - Time-Frequency Analysis Statistics','color',[1 1 1]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ANALISE TEMPORAL
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
[totaldeamostras,media,mediana,desviopadrao,minimo,...
      maximo,quartil1,quartil3,pnn50,rmssd,coefvar,faixadinamica]=temporalRR_calcula_stats(Y.RR(Y.normais));
%
texto1=sprintf([...
      '*********************\n',...
      '* TIME-DOMAIN STATS *\n',...
      '*********************\n\n',...
      'Minimum:             %0.5g ms\n',...
      'Maximum:             %0.5g ms\n',...
      'Dynamic Range:       %0.5g ms\n\n',...
   	  'Percentile 25:       %0.5g ms\n',...
      'Median:              %0.5g ms\n',...
      'Percentile 75:       %0.5g ms\n\n',...
      'Mean:                %0.5g ms\n',...
   	  'Standard Deviation:  %0.5g ms\n',...
      'Coeff. of Variance:  %0.5g %%\n\n',...
   	  'pNN50:               %0.5g %%\n',...
      'rMSSD:               %0.5g ms\n\n',...
      'Number of Intervals: %0.5g\n\n\n',...
	],...
   minimo,maximo,faixadinamica,quartil1,mediana,quartil3,media,desviopadrao,...
   coefvar,pnn50,rmssd,totaldeamostras);
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ANALISE ESPECTRAL
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
texto1=[texto1,espectralRR_sareas4(Y)];
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ESTATISTICA DA RAZAO LF/HF
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
[totaldeamostras,media,mediana,desviopadrao,minimo,...
      maximo,quartil1,quartil3,pnn50,rmssd,coefvar,faixadinamica]=temporalRR_calcula_stats(Y.rlfhf);
%
texto1=[texto1,sprintf([...
      '*******************\n',...
      '*   LF/HF RATIO   *\n',...
      '*******************\n\n',...
      'Minimum:             %0.5g\n',...
      'Maximum:             %0.5g\n',...
      'Dynamic Range:       %0.5g\n\n',...
   	  'Percentile 25:       %0.5g\n',...
      'Median:              %0.5g\n',...
      'Percentile 75:       %0.5g\n\n',...
      'Mean:                %0.5g\n',...
   	  'Standard Deviation:  %0.5g\n',...
      'Coeff. of Variance:  %0.5g %%\n\n',...
      'Area greater than 1: %0.5g sec\n',...
      'Area less than 1:    %0.5g sec\n',...
      'Greater/Less Ratio:  %0.5g',...
	],...
   minimo,maximo,faixadinamica,quartil1,mediana,quartil3,media,desviopadrao,coefvar,Y.agt1,Y.alt1,Y.ragt1alt1)];
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ESTATISTICA DA POTENCIA VLF
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
[totaldeamostras,media,mediana,desviopadrao,minimo,...
      maximo,quartil1,quartil3,pnn50,rmssd,coefvar,faixadinamica]=temporalRR_calcula_stats(Y.aavlf);
%
texto2=sprintf([...
      '*******************\n',...
      '*  VLF POWER      *\n',...
      '*******************\n\n',...
      'Minimum:             %0.5g ms^2\n',...
      'Maximum:             %0.5g ms^2\n',...
      'Dynamic Range:       %0.5g ms^2\n\n',...
   	  'Percentile 25:       %0.5g ms^2\n',...
      'Median:              %0.5g ms^2\n',...
      'Percentile 75:       %0.5g ms^2\n\n',...
      'Mean:                %0.5g ms^2\n',...
   	  'Standard Deviation:  %0.5g ms^2\n',...
      'Coeff. of Variance:  %0.5g %%\n\n',...
   ],...
   minimo,maximo,faixadinamica,quartil1,mediana,quartil3,media,desviopadrao,coefvar);
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ESTATISTICA DA POTENCIA LF
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
[totaldeamostras,media,mediana,desviopadrao,minimo,...
      maximo,quartil1,quartil3,pnn50,rmssd,coefvar,faixadinamica]=temporalRR_calcula_stats(Y.aalf);
%
texto2=[texto2,sprintf([...
      '*******************\n',...
      '*   LF POWER      *\n',...
      '*******************\n\n',...
      'Minimum:             %0.5g ms^2\n',...
      'Maximum:             %0.5g ms^2\n',...
      'Dynamic Range:       %0.5g ms^2\n\n',...
   	  'Percentile 25:       %0.5g ms^2\n',...
      'Median:              %0.5g ms^2\n',...
      'Percentile 75:       %0.5g ms^2\n\n',...
      'Mean:                %0.5g ms^2\n',...
   	  'Standard Deviation:  %0.5g ms^2\n',...
      'Coeff. of Variance:  %0.5g %%\n\n',...
  ],...
   minimo,maximo,faixadinamica,quartil1,mediana,quartil3,media,desviopadrao,coefvar)];
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ESTATISTICA DA POTENCIA HF
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
[totaldeamostras,media,mediana,desviopadrao,minimo,...
      maximo,quartil1,quartil3,pnn50,rmssd,coefvar,faixadinamica]=temporalRR_calcula_stats(Y.aahf);
%
texto2=[texto2,sprintf([...
      '*******************\n',...
      '*   HF POWER      *\n',...
      '*******************\n\n',...
      'Minimum:             %0.5g ms^2\n',...
      'Maximum:             %0.5g ms^2\n',...
      'Dynamic Range:       %0.5g ms^2\n\n',...
   	  'Percentile 25:       %0.5g ms^2\n',...
      'Median:              %0.5g ms^2\n',...
      'Percentile 75:       %0.5g ms^2\n\n',...
      'Mean:                %0.5g ms^2\n',...
   	  'Standard Deviation:  %0.5g ms^2\n',...
      'Coeff. of Variance:  %0.5g %%\n\n',...
	],...
   minimo,maximo,faixadinamica,quartil1,mediana,quartil3,media,desviopadrao,coefvar)];
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ESTATISTICA DA POTENCIA TOTAL
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
[totaldeamostras,media,mediana,desviopadrao,minimo,...
      maximo,quartil1,quartil3,pnn50,rmssd,coefvar,faixadinamica]=temporalRR_calcula_stats(Y.aatotal);
%
texto2=[texto2,sprintf([...
      '*******************\n',...
      '* TOTAL POWER     *\n',...
      '*******************\n\n',...
      'Minimum:             %0.5g ms^2\n',...
      'Maximum:             %0.5g ms^2\n',...
      'Dynamic Range:       %0.5g ms^2\n\n',...
   	  'Percentile 25:       %0.5g ms^2\n',...
      'Median:              %0.5g ms^2\n',...
      'Percentile 75:       %0.5g ms^2\n\n',...
      'Mean:                %0.5g ms^2\n',...
   	  'Standard Deviation:  %0.5g ms^2\n',...
      'Coeff. of Variance:  %0.5g %%\n\n',...
	],...
   minimo,maximo,faixadinamica,quartil1,mediana,quartil3,media,desviopadrao,coefvar)];
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ESTATISTICA DA POTENCIA RELATIVA VLF
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
[totaldeamostras,media,mediana,desviopadrao,minimo,...
      maximo,quartil1,quartil3,pnn50,rmssd,coefvar,faixadinamica]=temporalRR_calcula_stats(Y.avlf);
%
texto3=sprintf([...
      '********************\n',...
      '* VLF POWER (%%)    *\n',...
      '********************\n\n',...
      'Minimum:            %0.5g %%\n',...
      'Maximum:            %0.5g %%\n',...
      'Dynamic Range:      %0.5g %%\n\n',...
   	  'Percentile 25:      %0.5g %%\n',...
      'Median:             %0.5g %%\n',...
      'Percentile 75:      %0.5g %%\n\n',...
      'Mean:               %0.5g %%\n',...
   	  'Standard Deviation: %0.5g %%\n',...
      'Coeff. of Variance: %0.5g %%\n\n\n',...
	],...
   minimo,maximo,faixadinamica,quartil1,mediana,quartil3,media,desviopadrao,coefvar);
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ESTATISTICA DA POTENCIA RELATIVA LF
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
[totaldeamostras,media,mediana,desviopadrao,minimo,...
      maximo,quartil1,quartil3,pnn50,rmssd,coefvar,faixadinamica]=temporalRR_calcula_stats(Y.alf);
%
texto3=[texto3,sprintf([...
      '*******************\n',...
      '* LF POWER (%%)    *\n',...
      '*******************\n\n',...
      'Minimum:            %0.5g %%\n',...
      'Maximum:            %0.5g %%\n',...
      'Dynamic Range:      %0.5g %%\n\n',...
   	  'Percentile 25:      %0.5g %%\n',...
      'Median:             %0.5g %%\n',...
      'Percentile 75:      %0.5g %%\n\n',...
      'Mean:               %0.5g %%\n',...
   	  'Standard Deviation: %0.5g %%\n',...
      'Coeff. of Variance: %0.5g %%\n\n\n',...
	],...
   minimo,maximo,faixadinamica,quartil1,mediana,quartil3,media,desviopadrao,coefvar)];
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ESTATISTICA DA POTENCIA RELATIVA HF
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
[totaldeamostras,media,mediana,desviopadrao,minimo,...
      maximo,quartil1,quartil3,pnn50,rmssd,coefvar,faixadinamica]=temporalRR_calcula_stats(Y.ahf);
%
texto3=[texto3,sprintf([...
      '*******************\n',...
      '* HF POWER (%%)    *\n',...
      '*******************\n\n',...
      'Minimum:            %0.5g %%\n',...
      'Maximum:            %0.5g %%\n',...
      'Dynamic Range:      %0.5g %%\n\n',...
   	  'Percentile 25:      %0.5g %%\n',...
      'Median:             %0.5g %%\n',...
      'Percentile 75:      %0.5g %%\n\n',...
      'Mean:               %0.5g %%\n',...
   	  'Standard Deviation: %0.5g %%\n',...
      'Coeff. of Variance: %0.5g %%\n\n\n',...
	],...
   minimo,maximo,faixadinamica,quartil1,mediana,quartil3,media,desviopadrao,coefvar)];
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

texto3 = [texto3, sprintf('\n\n\n\n\n\n\n\n\n\nNumber of Windows:  %0.5g',totaldeamostras)];

uicontrol('Style','text','Position',[20  20   200   530],...
   'Visible','on','Hor','left','backgr',[1 1 1],...
	'Fontname','Terminal','FontSize',6,'String',texto1);

uicontrol('Style','text','Position',[240  20   200  530],...
   'Visible','on','Hor','left','backgr',[1 1 1],...
   'Fontname','Terminal','FontSize',6,'String',texto2);

uicontrol('Style','text','Position',[460  20   180   530],...
   'Visible','on','Hor','left','backgr',[1 1 1],...
	'Fontname','Terminal','FontSize',6,'String',texto3);