% PARA INSTRUCOES SOBRE USO, LEIA O ARQUIVO ECGFILT_README.DOC
%
%
clear %limpa a memoria do matlab

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% lista das variaveis globais
%

global samplerate_ecg

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%estes parametros podem ser facilmente alterados para personalizacao:
%

numerodajanela=100; %numero da figura do MatLab a ser usada como janela principal
fig_largura=1024;fig_altura=702; %largura e altura da janela do programa

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% cria a tela do programa
%
figure(numerodajanela);close(numerodajanela);
main_window=figure(numerodajanela);
clf;
set(main_window,'Name','(GPDS/ENE/UnB) ECGLAB - ECG Filtering','Position',[1,29,fig_largura,fig_altura])

mensageminicial=sprintf([...
      'ECGLAB - ECG Filtering Module\n\n\n',...
      'João Luiz Azevedo de Carvalho, Ph.D.\n\n\n',...
      'Digital Signal Processing Group\n',...
      'Department of Electrical Engineering\n',...
      'School of Technology\n',...      
      'University of Brasilia\n\n\n',...
      'joaoluiz@gmail.com',...
]);      
tx_mensagem=uicontrol('Style','text','String',mensageminicial,'Position',[100 150 800 500],'FontSize',14,...
   'HorizontalAlignment','center','BackgroundColor',[.8 .8 .8]);   

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%inicializacao de variaveis
%
fid=fopen('samplerate_ecg.cfg','r');samplerate_ecg=str2num(fgetl(fid));fclose(fid); %taxa de amostragem do ECGCapt
fid=fopen('filename.cfg','r');filename=fgetl(fid);fclose(fid); % nome do arquivo a ser aberto
ponto=find(filename=='.');filename=[filename(1:ponto(length(ponto))-1),'.mat']; %adapta a extensao
fid=fopen('segundos_janela.cfg','r');segundos_janela=str2num(fgetl(fid));fclose(fid); %janela de tempo mostrada no grafico
ecg_handle=-1; %handle do grafico do ecg
segundo=0; %posicao inicial do grafico
ecg_sinal=-1; %sinal de ECG
ecg_eventos=[]; %eventos no ECG
segundos_sinal=-1; %tamanho do ECG em segundos
ecg_totalsamples=-1; %numero total de amostras do ECG
largura60hz=10;
corteEMG=35;
corteLB=0.05;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: abrir arquivo
%

%frame
fr_abrirarquivo=uicontrol('Style','frame','Position',[80 20 560 60]);

%texto pedindo o nome do arquivo
tx_file=uicontrol('Style','text',...
   'String','Enter the full path to the ECG file to be opened:',...
   'Position',[90 50 300 20]);

%text edit para entrar com o nome do arquivo
te_file=uicontrol('Style','edit',...
   'String',cd,...
   'Position',[90 30 400 20],...
	'CallBack',[...
      'filename=get(te_file,''String'');',...
      'set(te_file,''String'',filename);',...
		'fid=fopen(''filename.cfg'',''w'');fwrite(fid,filename,''char'');fclose(fid);',...
	]);

%botao para abrir o arquivo
pb_abrir=uicontrol('Style','pushbutton',...
   'String','OPEN',...
   'Position',[500 30 60 30],...
   'CallBack',	[...
       'set(tx_mensagem,''Visible'',''off'');',...
       'filename=get(te_file,''String'');',...
	   '[ecg_sinal, ecg_eventos, ecg_ondar, ebs_indices, ecg_totalsamples,',...
            'segundos_sinal, janelas]=ecglabRR_abrir(filename,segundos_janela);',...
     	'if ecg_totalsamples==-1,',...
  			'set(tx_ecgerror,''String'',ecg_sinal,''Visible'',''on'');',...
			'ecg_sinal=-1;',...
			'if ecg_handle~=-1, delete(ecg_handle);ecg_handle=-1;end,',...
      	'set(fr_slider, ''Visible'', ''off'');',...      
     		'set(tx_janela_min, ''Visible'', ''off'');',...      
  			'set(sb_janela, ''Visible'', ''off'');',...      
			'set(tx_janela_max, ''Visible'', ''off'');',...      
			'set(tx_janela_lab, ''Visible'', ''off'');',...      
     	   'set(te_janela_cur, ''Visible'', ''off'');',...
     		'set(tx_deslocamento, ''Visible'', ''off'');',...
         'set(te_deslocamento, ''Visible'', ''off'');',...
  	   	'set(pb_deslocaesq, ''Visible'', ''off'');',...
         'set(pb_deslocadir, ''Visible'', ''off'');',...
         'set(pb_salvar, ''Visible'', ''off'');',...
         'set(fr_filtra60hz, ''Visible'', ''off'');',...
         'set(tx_filtra60hz, ''Visible'', ''off'');',...
         'set(te_filtra60hz, ''Visible'', ''off'');',...
         'set(tx_filtra60hz2, ''Visible'', ''off'');',...
         'set(pb_filtra60hz, ''Visible'', ''off'');',...
         'set(fr_filtraEMG, ''Visible'', ''off'');',...
         'set(tx_filtraEMG, ''Visible'', ''off'');',...
         'set(te_filtraEMG, ''Visible'', ''off'');',...
         'set(tx_filtraEMG2, ''Visible'', ''off'');',...
         'set(pb_filtraEMG, ''Visible'', ''off'');',...
         'set(fr_filtraLB, ''Visible'', ''off'');',...
         'set(tx_filtraLB, ''Visible'', ''off'');',...
         'set(te_filtraLB, ''Visible'', ''off'');',...
         'set(tx_filtraLB2, ''Visible'', ''off'');',...
         'set(pb_filtraLB, ''Visible'', ''off'');',...
      'else ',...
			'segundo=0;',...
  			'set(tx_ecgerror,''Visible'',''off'');',...
     	   'if segundos_sinal-segundos_janela > 0,',...
      		'set(sb_janela,''Max'',segundos_sinal-segundos_janela,''Value'',0);',...
         'else,',...   
         	'segundos_janela=segundos_sinal;',...
            'set(te_deslocamento,''String'',num2str(segundos_janela));',...
		   	'fid=fopen(''segundos_janela.cfg'',''w'');fwrite(fid,num2str(segundos_janela),''char'');fclose(fid);',...   
      		'set(sb_janela,''Max'',0,''Value'',0);',...
			'end,',...         
         'ecg_handle=ecgfilt_plotasinal(ecg_sinal,ecg_eventos, segundo, ecg_handle,segundos_janela,main_window);',...
      	'set(tx_janela_max, ''String'',[''Max='',num2str(segundos_sinal), ''s'']);',...
  	   	'segundo=0;',...
     		'set(te_janela_cur, ''String'',num2str(segundo));',...
   		'set(fr_slider, ''Visible'', ''on'');',...      
      	'set(tx_janela_min, ''Visible'', ''on'');',...      
	  		'set(sb_janela, ''Visible'', ''on'');',...      
			'set(tx_janela_max, ''Visible'', ''on'');',...      
			'set(tx_janela_lab, ''Visible'', ''on'');',...      
         'set(te_janela_cur, ''Visible'', ''on'');',...
  	   	'set(tx_deslocamento, ''Visible'', ''on'');',...
     	   'set(te_deslocamento, ''Visible'', ''on'');',...
     		'set(pb_deslocaesq, ''Visible'', ''on'');',...
         'set(pb_deslocadir, ''Visible'', ''on'');',...
         'set(pb_salvar, ''Visible'', ''on'');',...
         'set(fr_filtra60hz, ''Visible'', ''on'');',...
         'set(tx_filtra60hz, ''Visible'', ''on'');',...
         'set(te_filtra60hz, ''Visible'', ''on'');',...
         'set(tx_filtra60hz2, ''Visible'', ''on'');',...
         'set(pb_filtra60hz, ''Visible'', ''on'');',...
         'set(fr_filtraEMG, ''Visible'', ''on'');',...
         'set(tx_filtraEMG, ''Visible'', ''on'');',...
         'set(te_filtraEMG, ''Visible'', ''on'');',...
         'set(tx_filtraEMG2, ''Visible'', ''on'');',...
         'set(pb_filtraEMG, ''Visible'', ''on'');',...
         'set(fr_filtraLB, ''Visible'', ''on'');',...
         'set(tx_filtraLB, ''Visible'', ''on'');',...
         'set(te_filtraLB, ''Visible'', ''on'');',...
         'set(tx_filtraLB2, ''Visible'', ''on'');',...
         'set(pb_filtraLB, ''Visible'', ''on'');',...
     	'end,',...
		]);      
   
%mensagem de erro do abre arquivo ecg
tx_ecgerror=uicontrol('Style','text',...
   'Position',[80 140 500 40],...
   'Visible','off',...
   'String', ' ');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5
% GUI: BOTAO PARA SALVAR ECG
%%
pb_salvar=uicontrol('Style','pushbutton',...
   'String','SAVE','Visible','off',...
   'Position',[570 30 60 30],...
   'CallBack',	[...
      'ecgfilt_salvasinal(filename,ecg_sinal,ecg_eventos);',...
      'ponto=find(filename==''.'');filename=[filename(1:ponto(length(ponto))-1),''_filtered.mat''];',...
      'fid=fopen(''filename.cfg'',''w'');fwrite(fid,filename,''char'');fclose(fid);',...
      ]);



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: visualizacao do ECG
%

%frame do slider
fr_slider=uicontrol('Style','frame','Position',[80 100 760 70],'Visible','off');

%label do minimo do slider
tx_janela_min=uicontrol('Style','text',...
   'Position',[90 140 40 20],...
   'String','Min=0s',...
	'Visible','off');

%slider que desloca o sinal
sb_janela=uicontrol('Style','slider','Position',[130 140 620 20],...
   'Min',0,'Max',1,...
	'Visible','off',...
	'CallBack', [...
		'segundo=round(1000*get(sb_janela,''Value''))/1000;',...     
      'ecg_handle=ecgfilt_plotasinal(ecg_sinal,ecg_eventos, segundo, ecg_handle,segundos_janela,main_window);',...
      'set(te_janela_cur, ''String'',num2str(segundo));']);

%label do maximo do slider
tx_janela_max=uicontrol('Style','text',...
   'Position',[750 140 80 20],...
   'String','Max=0s',...
   'HorizontalAlignment', 'left',...
	'Visible','off');

%label do slider (janela atual)
tx_janela_lab=uicontrol('Style','text',...
   'Position',[90 110 70 20],...
   'String','Cur. Position:',...
	'Visible','off');

%text edit que mostra/modifica a posicao da janela atual
te_janela_cur=uicontrol('Style','edit',...
   'Position',[160 110 60 20],...
   'String','0',...
   'Visible','off',...
   'CallBack',[...
      'A=str2num(get(te_janela_cur,''String''));',...
      'if length(A)==1,',...
	   	'if A(1) <= get(sb_janela,''Max'') & A(1)>=0,',...
   			'set(sb_janela,''Value'',A(1));',...
         'elseif A(1)<=get(sb_janela,''Max'')+segundos_janela & A(1)>=0,',...
   			'set(sb_janela,''Value'',get(sb_janela,''Max''));',...
	      'end,',...
   	   'segundo=round(1000*get(sb_janela,''Value''))/1000;',...     
		   'ecg_handle=ecgfilt_plotasinal(ecg_sinal,ecg_eventos, segundo, ecg_handle,segundos_janela,main_window);',...         
   	'end,',...
      'set(te_janela_cur, ''String'',num2str(segundo));']);

%label do campo de deslocamento
tx_deslocamento=uicontrol('Style','text',...
   'Position',[245 110 80 20],...
   'String','Window Length:',...
   'Visible','off');

%botao que desloca uma janela para esquerda
pb_deslocaesq=uicontrol('Style','pushbutton',...
   'String','<',...
	'Position',[330 110 20 20],...
   'Visible','off',...
   'Callback',[...
         'if segundo-segundos_janela >= 0,',...
	   		'segundo=segundo-segundos_janela;',...
      	'else,',...
         	'segundo=0;',...
         'end,',... 
         'set(sb_janela,''Value'',segundo);',...  
	      'ecg_handle=ecgfilt_plotasinal(ecg_sinal,ecg_eventos, segundo, ecg_handle,segundos_janela,main_window);',...
   		'set(te_janela_cur, ''String'',num2str(segundo));']);

%text edit para determinar o tamanho da janela de deslocamento
te_deslocamento=uicontrol('Style','edit',...
   'Position',[350 110 40 20],...
   'Value', segundos_janela,...
	'String',num2str(segundos_janela),...
   'Visible','off',...
   'Callback',[...
      'A=str2num(get(te_deslocamento,''String''));',...
      'if (length(A)==1) & (A(1) >= 1/samplerate_ecg) & (A<=segundos_sinal),',...
	      'segundos_janela=round(1000*A(1))/1000;',...     
      	'if A(1)+segundo>=segundos_sinal,',...
            'segundo=segundos_sinal-segundos_janela;',...
            'set(te_janela_cur,''String'',num2str(segundo));',...
            'set(sb_janela,''Value'',segundo);',...
         'end,',...
      	'if segundos_sinal-segundos_janela > 0,',...
	      	'set(sb_janela,''Max'',segundos_sinal-segundos_janela);',...
         'else,',...   
	      	'set(sb_janela,''Max'',0);',...
	    	'end,',...
	      'ecg_handle=ecgfilt_plotasinal(ecg_sinal,ecg_eventos, segundo, ecg_handle,segundos_janela,main_window);',...
      'end,',...
      'set(te_deslocamento,''String'',num2str(segundos_janela));',...
   	'fid=fopen(''segundos_janela.cfg'',''w'');fwrite(fid,num2str(segundos_janela),''char'');fclose(fid);',...   
	]);

%botao que desloca uma janela para direita
pb_deslocadir=uicontrol('Style','pushbutton',...
   'String','>',...
	'Position',[390 110 20 20],...
   'Visible','off',...
   'Callback',[...
         'if segundo+segundos_janela <= get(sb_janela,''Max''),',...
	   		'segundo=segundo+segundos_janela;',...
      	'else,',...
         	'segundo=get(sb_janela,''Max'');',...
         'end,',... 
         'set(sb_janela,''Value'',segundo);',...  
	      'ecg_handle=ecgfilt_plotasinal(ecg_sinal,ecg_eventos, segundo, ecg_handle,segundos_janela,main_window);',...         
   		'set(te_janela_cur, ''String'',num2str(segundo));']);
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%555
% BOTOES PARA FILTRAGEM
%
%

%FILTRA 60hZ
fr_filtra60hz=uicontrol('Style','frame','Position',[660 60 325 30],'Visible','off');
tx_filtra60hz=uicontrol('style','text',...
   'String','Width of Notch:','Visible','off',...
   'Position',[670 65 85 20]);
te_filtra60hz=uicontrol('style','edit',...
   'String',num2str(largura60hz),'Visible','off',...
   'Position',[755 65 30 20],...
   'Callback',[...
      'A=round(str2num(get(te_filtra60hz,''string'')));',...
      'if length(A)>0 & A(1)>0 & A(1)<=20,',...
      	'set(te_filtra60hz,''string'',num2str(A(1)));',...
			'largura60hz=A(1);',...
		'else,',...
      	'set(te_filtra60hz,''string'',num2str(largura60hz));',...
		'end;',...
	]);
tx_filtra60hz2=uicontrol('style','text',...
   'String','(1% to 20%)','Visible','off',...
   'Position',[785 65 70 20]);
pb_filtra60hz=uicontrol('Style','pushbutton',...
   'String','Filter 60 Hz','Visible','off',...
   'Position',[865 65 110 20],...
   'CallBack',	[...
      'ecg_sinal=ecgfilt_filtra60hz(ecg_sinal,largura60hz);',...
      'ecg_handle=ecgfilt_plotasinal(ecg_sinal,ecg_eventos, segundo, ecg_handle,segundos_janela,main_window);',...         
   ]);

%FILTRA EMG
fr_filtraEMG=uicontrol('Style','frame','Position',[660 31 325 30],'Visible','off');
tx_filtraEMG=uicontrol('style','text',...
   'String','Low-pass at:','Visible','off',...
   'Position',[670 36 85 20]);
te_filtraEMG=uicontrol('style','edit',...
   'String',num2str(corteEMG),'Visible','off',...
   'Position',[755 36 30 20],...
   'Callback',[...
      'A=round(str2num(get(te_filtraEMG,''string'')));',...
      'if length(A)>0 & A(1)>=20 & A(1)<=60,',...
   		'set(te_filtraEMG,''string'',num2str(A(1)));',...
			'corteEMG=A(1);',...
		'else,',...
      	'set(te_filtraEMG,''string'',num2str(corteEMG));',...
		'end;',...
	]);
tx_filtraEMG2=uicontrol('style','text',...
   'String','(20 to 60 Hz)','Visible','off',...
   'Position',[785 36 70 20]);
pb_filtraEMG=uicontrol('Style','pushbutton',...
   'String','Filter HF Noise','Visible','off',...
   'Position',[865 36 110 20],...
   'CallBack',	[...
      'ecg_sinal=ecgfilt_filtraEMG(ecg_sinal,corteEMG);',...
      'ecg_handle=ecgfilt_plotasinal(ecg_sinal,ecg_eventos, segundo, ecg_handle,segundos_janela,main_window);',...         
      ]);
   
%FILTRA LINHA DE BASE
fr_filtraLB=uicontrol('Style','frame','Position',[660 2 325 30],'Visible','off');
tx_filtraLB=uicontrol('style','text',...
   'String','High-pass at:','Visible','off',...
   'Position',[670 7 75 20]);
te_filtraLB=uicontrol('style','edit',...
   'String',num2str(corteLB),'Visible','off',...
   'Position',[745 7 40 20],...
   'Callback',[...
      'A=round(1000*str2num(get(te_filtraLB,''string'')))/1000;',...
      'if length(A)>0 & A(1)>=0.001 & A(1)<=1,',...
   		'set(te_filtraLB,''string'',num2str(A(1)));',...
			'corteLB=A(1);',...
		'else,',...
      	'set(te_filtraLB,''string'',num2str(corteLB));',...
		'end;',...
	]);
tx_filtraLB2=uicontrol('style','text',...
   'String','(0.001 to 1 Hz)','Visible','off',...
   'Position',[785 7 70 20]);
pb_filtraLB=uicontrol('Style','pushbutton',...
   'String','Filter Baseline Wander','Visible','off',...
   'Position',[865 7 110 20],...
   'CallBack',	[...
      'ecg_sinal=ecgfilt_filtraLB(ecg_sinal,corteLB);',...
      'ecg_handle=ecgfilt_plotasinal(ecg_sinal,ecg_eventos, segundo, ecg_handle,segundos_janela,main_window);',...         
      ]);