% PARA INSTRUCOES SOBRE USO, LEIA O ARQUIVO ECGLABRR_README.DOC
%
%
clear %limpa a memoria do matlab

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% lista das variaveis globais
%

global samplerate_ecg

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%estes parametros podem ser facilmente alterados para personalizacao:
%

numerodajanela=100; %numero da figura do MatLab a ser usada como janela principal
fig_largura=1024;fig_altura=702; %largura e altura da janela do programa

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% cria a tela do programa
%
figure(numerodajanela);%close(numerodajanela);
main_window=figure(numerodajanela);
clf;
set(main_window,'Name','(GPDS/ENE/UnB) ECGLAB - QRS Detection','Position',[1,29,fig_largura,fig_altura])

mensageminicial=sprintf([...
      'ECGLAB - QRS Detection Module\n\n\n',...
      'Jo?o Luiz Azevedo de Carvalho, Ph.D.\n\n\n',...
      'Digital Signal Processing Group\n',...
      'Department of Electrical Engineering\n',...
      'School of Technology\n',...      
      'University of Brasilia\n\n\n',...
      'joaoluiz@gmail.com',...
]);      
tx_mensagem=uicontrol('Style','text','String',mensageminicial,'Position',[100 150 800 500],'FontSize',14,...
   'HorizontalAlignment','center','BackgroundColor',[.8 .8 .8]);   

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%inicializacao de variaveis
%
fid=fopen('samplerate_ecg.cfg','r');samplerate_ecg=str2num(fgetl(fid));fclose(fid); %taxa de amostragem do ECGCapt
fid=fopen('filename.cfg','r');filename=fgetl(fid);fclose(fid); % nome do arquivo a ser aberto
ponto=find(filename=='.');filename=[filename(1:ponto(length(ponto))-1),'.mat']; %adapta a extensao
fid=fopen('segundos_janela.cfg','r');segundos_janela=str2num(fgetl(fid));fclose(fid); %janela de tempo mostrada no grafico
cursor=0; %mostrar ou nao o cursor para marcar as ondas R
ecg_handle=-1; %handle do grafico do ecg
segundo=0; %posicao inicial do grafico
ecg_sinal=-1; %sinal de ECG
ecg_ondar=[]; %marcacoes das ondas R (indices do sinal de ECG)
ecg_eventos=[]; %eventos no ECG
segundos_sinal=-1; %tamanho do ECG em segundos
ecg_totalsamples=-1; %numero total de amostras do ECG
linha=-1; %cursor de marcacao da onda R
ebs_indices=[];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: abrir arquivo
%

%frame
fr_abrirarquivo=uicontrol('Style','frame','Position',[80 20 490 60]);

%texto pedindo o nome do arquivo
tx_file=uicontrol('Style','text',...
   'String','Enter the full path to the ECG file to be opened:',...
   'Position',[90 50 300 20]);

%text edit para entrar com o nome do arquivo
te_file=uicontrol('Style','edit',...
   'String',cd,...
   'Position',[90 30 400 20],...
	'CallBack',[...
      'filename=get(te_file,''String'');',...
      'set(te_file,''String'',filename);',...
		'fid=fopen(''filename.cfg'',''w'');fwrite(fid,filename,''char'');fclose(fid);',...
	]);

%botao para abrir o arquivo
pb_abrir=uicontrol('Style','pushbutton',...
   'String','OPEN',...
   'Position',[500 30 60 30],...
   'CallBack',	[...
      'filename=get(te_file,''String'');',...
	   '[ecg_sinal, ecg_eventos, ecg_ondar, ebs_indices, ecg_totalsamples,',...
            'segundos_sinal, janelas]=ecglabRR_abrir(filename,segundos_janela);',...
     	'if ecg_totalsamples==-1,',...
  			'set(tx_ecgerror,''String'',ecg_sinal,''Visible'',''on'');',...
			'ecg_sinal=-1;',...
			'if ecg_handle~=-1, delete(ecg_handle);ecg_handle=-1;end,',...
      	'set(fr_slider, ''Visible'', ''off'');',...      
     		'set(tx_janela_min, ''Visible'', ''off'');',...      
  			'set(sb_janela, ''Visible'', ''off'');',...      
			'set(tx_janela_max, ''Visible'', ''off'');',...      
			'set(tx_janela_lab, ''Visible'', ''off'');',...      
     	   'set(te_janela_cur, ''Visible'', ''off'');',...
     		'set(tx_deslocamento, ''Visible'', ''off'');',...
         'set(te_deslocamento, ''Visible'', ''off'');',...
  	   	'set(pb_deslocaesq, ''Visible'', ''off'');',...
     	   'set(cb_cursor, ''Visible'', ''off'');',...
        	'set(pb_deslocadir, ''Visible'', ''off'');',...
         'set(pb_salvarr, ''Visible'', ''off'');',...
         'set(pb_marcareb, ''Visible'', ''off'');',...
         'set(pb_apagaeb, ''Visible'', ''off'');',...
     'else ',...
            'set(tx_mensagem,''Visible'',''off'');',...
			'segundo=0;',...
  			'set(tx_ecgerror,''Visible'',''off'');',...
     	   'if segundos_sinal-segundos_janela > 0,',...
      		'set(sb_janela,''Max'',segundos_sinal-segundos_janela,''Value'',0);',...
         'else,',...   
         	'segundos_janela=segundos_sinal;',...
            'set(te_deslocamento,''String'',num2str(segundos_janela));',...
		   	'fid=fopen(''segundos_janela.cfg'',''w'');fwrite(fid,num2str(segundos_janela),''char'');fclose(fid);',...   
      		'set(sb_janela,''Max'',0,''Value'',0);',...
			'end,',...         
         'ecg_handle=ecglabRR_plotasinal(ecg_sinal,ecg_eventos,ecg_ondar,ebs_indices,0,',...
  		     	'''ecg'',ecg_handle,segundos_janela,main_window);',...
      	'set(tx_janela_max, ''String'',[''Max='',num2str(segundos_sinal), ''s'']);',...
     		'set(te_janela_cur, ''String'',num2str(segundo));',...
   		'set(fr_slider, ''Visible'', ''on'');',...      
      	'set(tx_janela_min, ''Visible'', ''on'');',...      
	  		'set(sb_janela, ''Visible'', ''on'');',...      
			'set(tx_janela_max, ''Visible'', ''on'');',...      
			'set(tx_janela_lab, ''Visible'', ''on'');',...      
         'set(te_janela_cur, ''Visible'', ''on'');',...
  	   	'set(tx_deslocamento, ''Visible'', ''on'');',...
     	   'set(te_deslocamento, ''Visible'', ''on'');',...
     		'set(pb_deslocaesq, ''Visible'', ''on'');',...
         'set(pb_deslocadir, ''Visible'', ''on'');',...
  	      'set(cb_cursor, ''Visible'', ''on'');',...
         'set(pb_salvarr, ''Visible'', ''on'');',...
         'set(pb_marcareb, ''Visible'', ''on'');',...
         'set(pb_apagaeb, ''Visible'', ''on'');',...
     	'end,',...
      'set(tx_mensagens, ''String'', '' '');',...   
		]);      
   
%mensagem de erro do abre arquivo ecg
tx_ecgerror=uicontrol('Style','text',...
   'Position',[80 140 500 40],...
   'Visible','off',...
   'String', ' ');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: visualizacao do ECG
%

%frame do slider
fr_slider=uicontrol('Style','frame','Position',[80 100 760 70],'Visible','off');

%label do minimo do slider
tx_janela_min=uicontrol('Style','text',...
   'Position',[90 140 40 20],...
   'String','Min=0s',...
	'Visible','off');

%slider que desloca o sinal
sb_janela=uicontrol('Style','slider','Position',[130 140 620 20],...
   'Min',0,'Max',1,...
	'Visible','off',...
	'CallBack', [...
		'segundo=round(1000*get(sb_janela,''Value''))/1000;',...     
      'ecg_handle=ecglabRR_plotasinal(ecg_sinal,ecg_eventos,ecg_ondar,ebs_indices,',...
      	'segundo,''ecg'',ecg_handle,segundos_janela,main_window);',...
      'set(te_janela_cur, ''String'',num2str(segundo));']);

%label do maximo do slider
tx_janela_max=uicontrol('Style','text',...
   'Position',[750 140 80 20],...
   'String','Max=0s',...
   'HorizontalAlignment', 'left',...
	'Visible','off');

%label do slider (janela atual)
tx_janela_lab=uicontrol('Style','text',...
   'Position',[90 110 70 20],...
   'String','Cur. Position:',...
	'Visible','off');

%text edit que mostra/modifica a posicao da janela atual
te_janela_cur=uicontrol('Style','edit',...
   'Position',[160 110 60 20],...
   'String','0',...
   'Visible','off',...
   'CallBack',[...
      'A=str2num(get(te_janela_cur,''String''));',...
      'if length(A)==1,',...
	   	'if A(1) <= get(sb_janela,''Max'') & A(1)>=0,',...
   			'set(sb_janela,''Value'',A(1));',...
         'elseif A(1)<=get(sb_janela,''Max'')+segundos_janela & A(1)>=0,',...
   			'set(sb_janela,''Value'',get(sb_janela,''Max''));',...
	      'end,',...
   	   'segundo=round(1000*get(sb_janela,''Value''))/1000;',...     
      	'ecg_handle=ecglabRR_plotasinal(ecg_sinal,ecg_eventos,ecg_ondar,ebs_indices,',...
         	'segundo,''ecg'',ecg_handle,segundos_janela,main_window);',...
   	'end,',...
      'set(te_janela_cur, ''String'',num2str(segundo));']);

%label do campo de deslocamento
tx_deslocamento=uicontrol('Style','text',...
   'Position',[250 110 80 20],...
   'String','Window Length:',...
   'Visible','off');

%botao que desloca uma janela para esquerda
pb_deslocaesq=uicontrol('Style','pushbutton',...
   'String','<',...
	'Position',[330 110 20 20],...
   'Visible','off',...
   'Callback',[...
         'if segundo-segundos_janela >= 0,',...
	   		'segundo=segundo-segundos_janela;',...
      	'else,',...
         	'segundo=0;',...
         'end,',... 
         'set(sb_janela,''Value'',segundo);',...  
         'ecg_handle=ecglabRR_plotasinal(ecg_sinal,ecg_eventos,ecg_ondar,ebs_indices,segundo,''ecg'',',...
         	'ecg_handle,segundos_janela,main_window);',...
   		'set(te_janela_cur, ''String'',num2str(segundo));']);

%text edit para determinar o tamanho da janela de deslocamento
te_deslocamento=uicontrol('Style','edit',...
   'Position',[350 110 40 20],...
   'Value', segundos_janela,...
	'String',num2str(segundos_janela),...
   'Visible','off',...
   'Callback',[...
      'A=str2num(get(te_deslocamento,''String''));',...
      'if (length(A)==1) & (A(1) >= 1/samplerate_ecg) & (A<=segundos_sinal),',...
	      'segundos_janela=round(1000*A(1))/1000;',...     
      	'if A(1)+segundo>=segundos_sinal,',...
            'segundo=segundos_sinal-segundos_janela;',...
            'set(te_janela_cur,''String'',num2str(segundo));',...
            'set(sb_janela,''Value'',segundo);',...
         'end,',...
      	'if segundos_sinal-segundos_janela > 0,',...
	      	'set(sb_janela,''Max'',segundos_sinal-segundos_janela);',...
         'else,',...   
	      	'set(sb_janela,''Max'',0);',...
	    	'end,',...
          'ecg_handle=ecglabRR_plotasinal(ecg_sinal,ecg_eventos,ecg_ondar,ebs_indices,segundo,''ecg'',',...
          	'ecg_handle,segundos_janela,main_window);',...
      'end,',...
      'set(te_deslocamento,''String'',num2str(segundos_janela));',...
   	'fid=fopen(''segundos_janela.cfg'',''w'');fwrite(fid,num2str(segundos_janela),''char'');fclose(fid);',...   
	]);

%botao que desloca uma janela para direita
pb_deslocadir=uicontrol('Style','pushbutton',...
   'String','>',...
	'Position',[390 110 20 20],...
   'Visible','off',...
   'Callback',[...
         'if segundo+segundos_janela <= get(sb_janela,''Max''),',...
	   		'segundo=segundo+segundos_janela;',...
      	'else,',...
         	'segundo=get(sb_janela,''Max'');',...
         'end,',... 
         'set(sb_janela,''Value'',segundo);',...  
         'ecg_handle=ecglabRR_plotasinal(ecg_sinal,ecg_eventos,ecg_ondar,ebs_indices,segundo,''ecg'',',...
         	'ecg_handle,segundos_janela,main_window);',...
   		'set(te_janela_cur, ''String'',num2str(segundo));']);
   
%check box do cursor
cb_cursor=uicontrol(main_window,'Style','checkbox',...
   'Position',[450 110 90 20],...
   'String','Show cursor',...
   'Visible','off','Value',cursor,...
   'CallBack','cursor=~cursor;');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: caixa de mensagens
%
   
%borda em volta da caixa de texto de mensagens 
fr_mensagens=uicontrol('Style','frame','Position',[590 20 250 60]);
   
%caixa de texto para mensagens 'deteccao em andamento'
tx_mensagens=uicontrol('Style','text',...
   'Position',[600 30 230 40],...
   'String', ' ');   

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: botao para salvar marcacao e intervalos R-R
%

pb_marcareb=uicontrol('Style','pushbutton',...
   'String','Mark Ectopic',...
	'Position',[860 140 110 30],...
   'Visible','off',...
   'CallBack',[...
      'if length(ecg_ondar)>=2,',...
	   	'ebs_indices=ecglabRR_marcaeb(ebs_indices,ecg_ondar,ecg_sinal,segundo,segundos_janela);',...
         'ecg_handle=ecglabRR_plotasinal(ecg_sinal,ecg_eventos,ecg_ondar,ebs_indices,',...
         	'segundo,''ecg'',ecg_handle,segundos_janela,main_window);',...
      'else,',...   
    		'set(tx_mensagens, ''String'', ''Run QRS detection before doing that!'');',...   
      'end,']);

%[ondasQ,marcaq]=ecglabQT_marcaondaq(ondasQ,ecg_sinal,segundo,segundos_janela);


pb_apagaeb=uicontrol('Style','pushbutton',...
   'String','Unmark Ectopic',...
	'Position',[860 100 110 30],...
   'Visible','off',...
   'CallBack',[...
      'if isempty(ebs_indices)~=1,',...
	   	'ebs_indices=ecglabRR_apagaeb(ebs_indices,ecg_ondar,ecg_sinal,segundo,segundos_janela);',...
         'ecg_handle=ecglabRR_plotasinal(ecg_sinal,ecg_eventos,ecg_ondar,ebs_indices,',...
         	'segundo,''ecg'',ecg_handle,segundos_janela,main_window);',...
      'else,',...   
    		'set(tx_mensagens, ''String'', ''No heartbeat is currently marked as ectopic!'');',...   
      'end,']);

pb_salvarr=uicontrol('Style','pushbutton',...
   'String','SAVE',...
	'Position',[860 20 110 60],...
   'Visible','off',...
   'CallBack',[...
		'if ecg_totalsamples~=-1,','saveRR;'...      
      	'salva_ondar(ecg_ondar,filename,segundos_sinal,ebs_indices);',...
    		'set(tx_mensagens, ''String'', ''The markings and R-R intervals have been saved!'');',...   
      'else,',...   
    		'set(tx_mensagens, ''String'', ''There is no ECG currently opened!'');',...   
      'end,']);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: marcacao das ondas R com o mouse
%

%o movimento do cursor faz aparecer uma linha vertical
set(main_window, 'WindowButtonMotionFcn',[...
   'if cursor==1 & ecg_handle ~= -1,',...   
	   'if isempty(find(get(ecg_handle,''Children'')==linha))==1,linha=-1;end,',...
		'if linha~=-1,delete(linha);end,',...   
	   'ponto=get(ecg_handle,''CurrentPoint'');',...
   	'if ponto(1,1)>=segundo & ponto(1,1)<=segundo+segundos_janela ',...
	   	'& abs(ponto(2,2))<=1000,',...
   	   	'axes(ecg_handle);',...
      	   'linha=line([ponto(1,1) ponto(1,1)],[-1000 1000],',...
         		'''color'',[0.5 0.5 0.5],''LineStyle'',''-'');',...
	   'end,',...
	'end,']);

%os cliques no ecg apagam ou fazem marcacoes R   
set(main_window, 'WindowButtonDownfcn',[...
      'if ecg_handle ~= -1 & ecg_totalsamples~=-1,',...
      	'[ecg_ondar,ebs_indices]=ecglabRR_marcaondaR(ecg_sinal,ecg_ondar,ebs_indices,ecg_handle,',...
         	'segundo,segundos_janela,segundos_sinal);',...
         'ecg_handle=ecglabRR_plotasinal(ecg_sinal,ecg_eventos,ecg_ondar,ebs_indices,',...
         	'segundo,''ecg'',ecg_handle,segundos_janela,main_window);',...
      'end,']);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5
%
% MENU
%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%     
     
%neste menu, aparecem algumas funcoes relacioandas com o intervalo R-R deste ECG     
menu_iRR=uimenu(main_window,'Label','R-R Interval');

%submenu para detectar a onda R
subm_detecta_ondar=uimenu(menu_iRR,'Label','Detect R waves');
   
%submenu para detectar a onda R pelo algoritmo rapido
subm_detecta_ondar_rapido=uimenu(subm_detecta_ondar,'Label','Fast Algorithm',...
   'CallBack',	[...
		'if ecg_totalsamples~=-1,',...      
   	   'set(tx_mensagens, ''String'', ''QRS detection in progress, please wait!',...
	   	   ' '');',...
   		'[ecg_ondar,ebs_indices]=ecglabRR_detecta_ondar(ecg_sinal,''2'');',...
        	'ecg_handle=ecglabRR_plotasinal(ecg_sinal,ecg_eventos,ecg_ondar,ebs_indices,segundo,',...
        		'''ecg'',ecg_handle,segundos_janela,main_window);',...
         'set(tx_mensagens, ''String'', ''QRS detection completed! Please, ',...
         	'save the markings.'');',...   
      'else,',...   
    		'set(tx_mensagens, ''String'', ''No ECG currently opened!'');',...   
	   'end,']);

%submenu para detectar a onda R pelo algoritmo lento
subm_detecta_ondar_lento=uimenu(subm_detecta_ondar,'Label','Slow Algorithm',...
   'CallBack',	[...
		'if ecg_totalsamples~=-1,',...      
	      'set(tx_mensagens, ''String'', ''QRS detection in progress, please wait!',...
      		' '');',...
   		'[ecg_ondar,ebs_indices]=ecglabRR_detecta_ondar(ecg_sinal,''1'');ebs_indices=[];',...
        	'ecg_handle=ecglabRR_plotasinal(ecg_sinal,ecg_eventos,ecg_ondar,ebs_indices,segundo,',...
        		'''ecg'',ecg_handle,segundos_janela,main_window);',...
         'set(tx_mensagens, ''String'', ''QRS detection completed! Please, ',...
         	'save the markings.'');',...   
      'else,',...   
    		'set(tx_mensagens, ''String'', ''No ECG currently opened!'');',...   
	   'end,']);

%submenu que salva a marcacao R-R
subm_salvaRR=uimenu(menu_iRR,'Label','Save markings and R-R intervals',...
   'Separator','on','CallBack',get(pb_salvarr,'CallBack'));

%submenu que apaga as marcacoes R-R
subm_limpaRR=uimenu(menu_iRR,'Label','Clear all markings',...
   'CallBack',[...
		'if ecg_totalsamples~=-1,',...      
      	'ecg_ondar=[];ebs_indices=[];',...
         'ecg_handle=ecglabRR_plotasinal(ecg_sinal,ecg_eventos,ecg_ondar,ebs_indices,',...
         	'segundo,''ecg'',ecg_handle,segundos_janela,main_window);',...
      	'set(tx_mensagens, ''String'', ''R-wave markings cleared!'');',...   
      'else,',...   
    		'set(tx_mensagens, ''String'', ''No ECG currently opened!'');',...   
      'end,']);

%submenu que restaura as marcacoes R-R do disco
subm_restauraRR=uimenu(menu_iRR,'Label','Restore markings from disk',...
   'CallBack',[...
		'if ecg_totalsamples~=-1,',...      
      	'ecg_ondar=le_ondar(filename);',...
			'ebs_indices=ecglabRR_le_ebs(filename,segundos_sinal);',...
         'ecg_handle=ecglabRR_plotasinal(ecg_sinal,ecg_eventos,ecg_ondar,ebs_indices,',...
         	'segundo,''ecg'',ecg_handle,segundos_janela,main_window);',...
      	'set(tx_mensagens, ''String'', ''R-wave markings restored!'');',...   
      'else,',...   
    		'set(tx_mensagens, ''String'', ''No ECG currently opened!'');',...   
      'end,']);