% PARA INSTRUCOES SOBRE USO, LEIA O ARQUIVO ECTOPICS_README.DOC
%
%
clear %limpa a memoria do matlab

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%estes parametros podem ser facilmente alterados para personalizacao:
%

numerodajanela=100; %numero da figura do MatLab a ser usada como janela principal
fig_largura=1024;fig_altura=702; %largura e altura da janela do programa

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% cria a tela do programa
%
figure(numerodajanela);close(numerodajanela);
main_window=figure(numerodajanela);
clf;
set(main_window,'Name','(GPDS/ENE/UnB) ECGLAB - Identification of Ectopic Beats','Position',[1,29,fig_largura,fig_altura])

mensageminicial=sprintf([...
      'ECGLAB - Identification of Ectopic Beats\n\n\n',...
      'João Luiz Azevedo de Carvalho, Ph.D.\n\n\n',...
      'Digital Signal Processing Group\n',...
      'Department of Electrical Engineering\n',...
      'School of Technology\n',...      
      'University of Brasilia\n\n\n',...
      'joaoluiz@gmail.com',...
]);      
tx_mensagem=uicontrol('Style','text','String',mensageminicial,'Position',[100 150 800 500],'FontSize',14,...
   'HorizontalAlignment','center','BackgroundColor',[.8 .8 .8]);   

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%inicializacao de variaveis
%
fid=fopen('filename.cfg','r');filename=fgetl(fid);fclose(fid); % nome do arquivo a ser aberto
ponto=find(filename=='.');filename=[filename(1:ponto(length(ponto))-1),'.irr']; %adapta a extensao
eventos=[];
intervaloRR=-1;
tempoRR=-1;
verdadeiros=-1;
ebs_indices=[];
ebs_handle=-1;
limitex=0;eixox1=0;eixox2=0;
deslocamento=-1;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: abrir arquivo
%

%frame
fr_abrirarquivo=uicontrol('Style','frame','Position',[80 20 580 60]);

%texto pedindo o nome do arquivo
tx_file=uicontrol('Style','text',...
   'String','Enter the full path to the IRR or ASCII file to be opened:',...
   'Position',[90 50 300 20]);

%text edit para entrar com o nome do arquivo
te_file=uicontrol('Style','edit',...
   'String',filename,...
   'Position',[90 30 400 20],...
	'CallBack',[...
      'filename=get(te_file,''String'');',...
      'set(te_file,''String'',filename);',...
		'fid=fopen(''filename.cfg'',''w'');fwrite(fid,filename,''char'');fclose(fid);',...
	]);

%botao para abrir o arquivo
pb_abrir_irr=uicontrol('Style','pushbutton',...
   'String','Open IRR',...
   'Position',[500 30 70 30],...
   'CallBack',	[...
      'filename=get(te_file,''String'');',...
      '[intervaloRR,tempoRR,verdadeiros,ebs_indices]=le_IRR(filename);',...
		'if intervaloRR(1)~=-1,',...
   		'eventos=le_eventos(filename);',...
         'set(tx_mensagens, ''String'', '' '');',...
         'limitex=length(intervaloRR);eixox1=1;eixox2=limitex;',...
         'ebs_handle=ectopics_intervalograma(tempoRR,intervaloRR,ebs_indices,ebs_handle,eixox1,eixox2);',...
			'set(fr_marcacao,''Visible'',''on'');',...
			'set(pb_alg2,''Visible'',''on'');',...
			'set(pb_mmouse,''Visible'',''on'');',...
			'set(pb_cancelar,''Visible'',''on'');',...
         'set(pb_validar,''Visible'',''on'');',...
         'set(tx_labelx1,''Visible'',''on'');',...    
         'set(te_eixox1,''Visible'',''on'',''string'',num2str(eixox1));',...    
         'set(tx_labelx2,''Visible'',''on'');',...    
      	'set(te_eixox2,''Visible'',''on'',''string'',num2str(eixox2));',...    
         'set(tx_labelx4,''Visible'',''on'',''string'',num2str(limitex));',...    
         'set(tx_labelx5,''Visible'',''on'');',...
         'set(pb_select,''Visible'',''on'');',...
         'set(pb_esquerda,''Visible'',''on'');',...         
      	'set(pb_direita,''Visible'',''on'');',...         
        'set(tx_mensagem,''Visible'',''off'');',...
      'else,',...
	      'set(tx_mensagens, ''String'', ''This file does not contain R-R intervals!'');',...
         'eventos=[];',...
         'if ebs_handle~=-1, delete(ebs_handle);ebs_handle=-1;end,',...
			'set(fr_marcacao,''Visible'',''off'');',...
			'set(pb_alg2,''Visible'',''off'');',...
			'set(pb_mmouse,''Visible'',''off'');',...
         'set(pb_cancelar,''Visible'',''off'');',...
         'set(pb_validar,''Visible'',''off'');',...
         'set(tx_labelx1,''Visible'',''off'');',...    
         'set(te_eixox1,''Visible'',''off'');',...    
         'set(tx_labelx2,''Visible'',''off'');',...    
      	'set(te_eixox2,''Visible'',''off'');',...    
         'set(tx_labelx4,''Visible'',''off'');',...    
         'set(tx_labelx5,''Visible'',''off'');',...    
         'set(pb_select,''Visible'',''off'');',...
         'set(pb_esquerda,''Visible'',''off'');',...         
      	'set(pb_direita,''Visible'',''off'');',...    
        'set(tx_mensagem,''Visible'',''on'');',...
      'end,',...
		]);
   
%botao para abrir o arquivo
pb_abrir_ascii=uicontrol('Style','pushbutton',...
   'String','Open ASCII',...
   'Position',[580 30 70 30],...
   'CallBack',	[...
      'filename=get(te_file,''String'');',...
      '[intervaloRR,tempoRR,verdadeiros,ebs_indices]=le_IRR_ascii(filename);',...
		'if intervaloRR(1)~=-1,',...
   		'eventos=le_eventos(filename);',...
         'set(tx_mensagens, ''String'', '' '');',...
         'limitex=length(intervaloRR);eixox1=1;eixox2=limitex;',...         
         'ebs_handle=ectopics_intervalograma(tempoRR,intervaloRR,ebs_indices,ebs_handle,eixox1,eixox2);',...
			'set(fr_marcacao,''Visible'',''on'');',...
			'set(pb_alg2,''Visible'',''on'');',...
			'set(pb_mmouse,''Visible'',''on'');',...
			'set(pb_cancelar,''Visible'',''on'');',...
         'set(pb_validar,''Visible'',''on'');',...    
         'set(tx_labelx1,''Visible'',''on'');',...    
         'set(te_eixox1,''Visible'',''on'',''string'',num2str(eixox1));',...    
         'set(tx_labelx2,''Visible'',''on'');',...    
      	'set(te_eixox2,''Visible'',''on'',''string'',num2str(eixox2));',...    
         'set(tx_labelx4,''Visible'',''on'',''string'',num2str(limitex));',...    
         'set(tx_labelx5,''Visible'',''on'');',...
         'set(pb_select,''Visible'',''on'');',...
         'set(pb_esquerda,''Visible'',''on'');',...         
      	'set(pb_direita,''Visible'',''on'');',...
        'set(tx_mensagem,''Visible'',''off'');',...
      'else,',...
      	'set(tx_mensagens, ''String'', ''This file does not contain R-R intervals! ',...
      		'Each line must contain only 1 interval value!'');',...
         'eventos=[];',...
         'if ebs_handle~=-1, delete(ebs_handle);ebs_handle=-1;end,',...
      	'set(fr_marcacao,''Visible'',''off'');',...
        'set(tx_mensagem,''Visible'',''on'');',...
			'set(pb_alg2,''Visible'',''off'');',...
			'set(pb_mmouse,''Visible'',''off'');',...
			'set(pb_cancelar,''Visible'',''off'');',...
         'set(pb_validar,''Visible'',''off'');',...    
         'set(tx_labelx1,''Visible'',''off'');',...    
         'set(te_eixox1,''Visible'',''off'');',...    
         'set(tx_labelx2,''Visible'',''off'');',...    
      	'set(te_eixox2,''Visible'',''off'');',...    
         'set(tx_labelx4,''Visible'',''off'');',...    
         'set(tx_labelx5,''Visible'',''off'');',...    
         'set(pb_select,''Visible'',''off'');',...
         'set(pb_esquerda,''Visible'',''off'');',...         
      	'set(pb_direita,''Visible'',''off'');',...         
      'end,',...
		]);
   
   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: caixa de mensagens
%
   
%borda em volta da caixa de texto de mensagens 
fr_mensagens=uicontrol('Style','frame','Position',[680 20 300 60]);
   
%caixa de texto para mensagens
tx_mensagens=uicontrol('Style','text',...
   'Position',[690 30 280 40],...
   'String', ['IRR files are the ones obtained from ECGLabRR or EctopicsRR. R-R intervals in ASCII must ',...
      'contain a single interval value per line.']);   

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: botoes para marcacao dos intervalos
%

%frame
fr_marcacao=uicontrol('Style','frame','Position',[20 100 990 60],'Visible','off');

%botao para detectar com algoritmo 2
pb_alg2=uicontrol('Style','pushbutton',...
   'String','Automatic Detection',...
   'Position',[30 110 120 40],'Visible','off',...
   'CallBack',	[...
   	'ebs_indices=ectopics_marcaebs(intervaloRR,tempoRR);',...
      'ebs_handle=ectopics_intervalograma(tempoRR,intervaloRR,ebs_indices,ebs_handle,eixox1,eixox2);',...
	]);

%botao para marcar com mouse
pb_mmouse=uicontrol('Style','pushbutton',...
   'String','Mark/Unmark Interval (w/ MOUSE)',...
   'Position',[160 110 220 40],'Visible','off',...
   'CallBack',	[...
      'ebs_indices=ectopics_marcaeb_mouse(ebs_indices,intervaloRR,eixox1,eixox2);',...
      'ebs_handle=ectopics_intervalograma(tempoRR,intervaloRR,ebs_indices,ebs_handle,eixox1,eixox2);',...
	]);

%botao para apagar marcas
pb_cancelar=uicontrol('Style','pushbutton',...
   'String','CLEAR Markings',...
   'Position',[390 110 110 40],'Visible','off',...
   'CallBack',	[...
      'ebs_indices=[];',...
      'ebs_handle=ectopics_intervalograma(tempoRR,intervaloRR,ebs_indices,ebs_handle,eixox1,eixox2);',...
	]);

%botao para validar intervalos
pb_validar=uicontrol('Style','pushbutton',...
   'String','SAVE Ectopic Beat Markings',...
   'Position',[510 110 200 40],'Visible','off',...
   'CallBack',	[...
      'verdadeiros=1:length(intervaloRR);',...
      'for i=1:length(ebs_indices),',...
      	'verdadeiros=verdadeiros(find(verdadeiros~=ebs_indices(i)));',...
      'end,',...
      'salva_IRR(intervaloRR,tempoRR,verdadeiros,ebs_indices,filename);',...
      'eixox1=1;eixox2=limitex;',...
      'set(te_eixox1,''string'',num2str(eixox1));',...    
    	'set(te_eixox2,''string'',num2str(eixox2));',...    
      'ebs_handle=ectopics_intervalograma2(tempoRR,intervaloRR,ebs_indices,verdadeiros,ebs_handle);',...
   ]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: limites do intervalograma
%

% caixas de texto (label)
tx_labelx1=uicontrol('Visible','off','Style','text',...
   'String','De',...
   'Position',[790-35 130 13 20]);

% caixas de edicao de texto (pontos iniciais do grafico)
te_eixox1=uicontrol('Visible','off','Style','edit',...
   'Position',[808-35 130 40 20],...
   'Value', eixox1,...
	'String',num2str(eixox1),...
   'Callback',[...
      'A=str2num(get(te_eixox1,''String''));',...
      'if length(A)==1,',...
	   	'if A < eixox2-1 & A >=1,',...
         	'eixox1=floor(A);',... %tira as casas decimais
	      'end,',...
   	'end,',...
      'set(te_eixox1,''String'',num2str(eixox1));',...
      'ebs_handle=ectopics_intervalograma(tempoRR,intervaloRR,ebs_indices,ebs_handle,eixox1,eixox2);',...
	]);

% caixas de texto (label)
tx_labelx2=uicontrol('Visible','off','Style','text',...
   'String','a',...
   'Position',[853-35 130 10 20]);

% caixas de edicao de texto (pontos finais do grafico)
te_eixox2=uicontrol('Visible','off','Style','edit',...
   'Position',[868-35 130 40 20],...
   'Value', eixox2,...
	'String',num2str(eixox2),...
   'Callback',[...
      'A=str2num(get(te_eixox2,''String''));',...
      'if length(A)==1,',...
	   	'if A <= limitex & A >eixox1+1,',...
         	'eixox2=ceil(A);',... %tira as casas decimais
	      'end,',...
   	'end,',...
      'set(te_eixox2,''String'',num2str(eixox2));',...
      'ebs_handle=ectopics_intervalograma(tempoRR,intervaloRR,ebs_indices,ebs_handle,eixox1,eixox2);',...
	]);

tx_labelx5=uicontrol('Visible','off','Style','text',...
   'String','min: 1     max:',...
	'Position',[808-35 113 65 13]);

tx_labelx4=uicontrol('Visible','off','Style','text',...
   'String','XXXX',...
   'Hor','left',...
   'Position',[878-35 113 41 13]);

pb_select=uicontrol('Visible','off','Style','push','position',[885 110 115 40],...
   'string','Select SEGMENT','CallBack',[...
	'intervaloRR=intervaloRR(eixox1:eixox2);tempoRR=tempoRR(eixox1:eixox2);',...
   'ebs_indices=ebs_indices-eixox1+1;',...
	'ebs_indices=ebs_indices(find( ebs_indices>=1 & ebs_indices<=length(intervaloRR) ));',...
	'eixox1=1;eixox2=length(intervaloRR);limitex=eixox2;',...
   'set(te_eixox1,''String'',num2str(eixox1));',...
	'set(te_eixox2,''String'',num2str(eixox2));',...
   'set(tx_labelx4,''String'',num2str(limitex));',...
   'ebs_handle=ectopics_intervalograma(tempoRR,intervaloRR,ebs_indices,ebs_handle,eixox1,eixox2);',...
]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% GUI: botoes para deslocar o intervalograma
%

pb_esquerda=uicontrol('Visible','off','style','push','position',[720 110 15 20],...
   'string','<','CallBack',[...
      'deslocamento=eixox2-eixox1;',...
      'if eixox1-deslocamento>=1,eixox2=eixox1;eixox1=eixox1-deslocamento;',...
      'else,eixox1=1;eixox2=1+deslocamento;end,',...
      'set(te_eixox1,''String'',num2str(eixox1));',...
      'set(te_eixox2,''String'',num2str(eixox2));',...      
      'ebs_handle=ectopics_intervalograma(tempoRR,intervaloRR,ebs_indices,ebs_handle,eixox1,eixox2);',...      
   ]);

pb_direita=uicontrol('Visible','off','style','push','position',[740 110 15 20],...
   'string','>','CallBack',[...
      'deslocamento=eixox2-eixox1;',...
      'if eixox2+deslocamento<=limitex,eixox1=eixox2;eixox2=eixox2+deslocamento;',...
      'else,eixox2=limitex;eixox1=limitex-deslocamento;end,',...
      'set(te_eixox1,''String'',num2str(eixox1));',...
      'set(te_eixox2,''String'',num2str(eixox2));',...      
      'ebs_handle=ectopics_intervalograma(tempoRR,intervaloRR,ebs_indices,ebs_handle,eixox1,eixox2);',...      
   ]);

