function poincareRR_gera_html(filename,prontuario,intervaloRR,eixo1,eixo2,precisaopct,sds,incl,pcts,reta)
%usage:

imagenspb='n'; %imagens em preto e branco? [s/n]
tamanho_imagens=.8; %em porcentagem do tamanho original (recomendado: 0.3)
titulo_html='ECGLAB - Poincaré Plot Analysis of R-R Intervals';

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Este trecho corrige o path e determina o nome do arquivo de acordo com a extensao
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

ponto=find(filename=='.');
pathfilename=[filename(1:ponto(length(ponto))-1),'_prr'];

barras=find(pathfilename=='\');
filename=pathfilename(barras(length(barras))+1:length(pathfilename));
path=pathfilename(1:barras(length(barras)));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Este trecho gera o header e o final do arquivo HTML
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


html_header=['',...
      '<html>\n',...
      '<head>\n',...
      '<title>',titulo_html,'</title>\n',...
      '</head>\n',...
      '<body>\n',...
      '\n',...
	];

html_end='\n</body>\n</html>';

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Este trecho mostra o prontuario
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

prontuario=sprintf(prontuario);   
quebra_linha=find(prontuario==10);

if length(prontuario)<=1,
   html_prontuario='';
else
	if isempty(quebra_linha)~=1,

		for i=length(quebra_linha):-1:1,
   		if quebra_linha(i)>1 & quebra_linha(i)<length(prontuario),
      		prontuario=[prontuario(1:quebra_linha(i)-1),'<br>\n',prontuario(quebra_linha(i)+1:length(prontuario))];
		   elseif quebra_linha(i)==1,
   		   prontuario=['<br>\n',prontuario(quebra_linha(i)+1:length(prontuario))];
		   else
   		   if quebra_linha(i)>1 & quebra_linha(i)==length(prontuario),
      		   prontuario=[prontuario(1:quebra_linha(i)-1)];
		      end
   	   end      
		end
   
	end

	html_prontuario=[...
		'<div align="center"><center><table border="1" width="500"><tr><td><font face="Arial" size="2">\n',...
		prontuario,...
		'</font></td></tr></table></center></div>&nbsp;',...
		];

end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Este trecho gera um arquivo bmp com o grafico
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

indices=poincareRR_grafico2(intervaloRR,eixo1,eixo2,precisaopct,pcts,sds,incl,reta);
                     
print temp -f101 -dtiff -r100;
close(101);
figura_psd=imread('temp.tif','tif');
delete temp.tif;

%recorta a figura na parte do desenho esquematico
figura_psd=figura_psd(119:599,1:500,:);

figura_psd=imresize(figura_psd,tamanho_imagens,'bilinear');
if imagenspb=='s',
   figura_psd=rgb2gray(figura_psd);
end
imwrite(figura_psd,[pathfilename,'.bmp'],'bmp');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Este trecho gera o codigo HTML para mostrar o grafico
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

html_espectrograma=['\n<p align="center"><img border="0" src="',...
   [filename,'.bmp'],'"><br><br>\n'];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Este trecho gera o codigo HTML para mostrar os indices espectrais
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%indices=[length(RR),RRmedio,sd1,sd2,rvl,elipse,coef_corr,coef_regr,b,...
%			pct10,pts10,max10,min10,faixa10,rdisp10,quartil110,mediana10,quartil310,media10,dp10,cv10,...
%			pct25,pts25,max25,min25,faixa25,rdisp25,quartil125,mediana25,quartil325,media25,dp25,cv25,...
%			pct50,pts50,max50,min50,faixa50,rdisp50,quartil150,mediana50,quartil350,media50,dp50,cv50,...
%			pct75,pts75,max75,min75,faixa75,rdisp75,quartil175,mediana75,quartil375,media75,dp75,cv75,...
%			pct90,pts90,max90,min90,faixa90,rdisp90,quartil190,mediana90,quartil390,media90,dp90,cv90];

if reta(1)=='r'
   reta='Basis for Deviations: Regression Line';
else
   reta='Basis for Deviations: Identity Line';
end   
   
html_indicesfreq=['<div align="center"><center><table border="1" width="500">\n',...
      '<tr><td><font face="Arial" size="2"><br>&nbsp;&nbsp;&nbsp;&nbsp;Poincaré Plot Stats:\n',...
      '<br>&nbsp;</font></td></tr>',...
      '<tr><td><font face="Arial" size="2"><br>',...
   	'&nbsp;&nbsp;&nbsp;&nbsp;Number of Points: ',num2str(indices(1)),'<br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;Centroid: (',num2str(real(indices(2))),',',num2str(imag(indices(2))),') ms<br><br>\n',...
   	'&nbsp;&nbsp;&nbsp;&nbsp;',reta,'<br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;Vertical Deviation (SD1): ',num2str(indices(3)),' ms<br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;Longitudinal Deviation (SD2): ',num2str(indices(4)),' ms<br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;SD1/SD2 Ratio: ',num2str(indices(5)),'<br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;Area of Ellipse: ',num2str(indices(6)),' ms²<br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;Correlation Coefficient: ',num2str(indices(7)),'<br>\n',...
   	'&nbsp;&nbsp;&nbsp;&nbsp;Regression Coefficient: ',num2str(indices(8)),'<br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;Equation of Regression Line: RRn+1 = ',num2str(indices(8)),' RRn + ',num2str(indices(9)),'\n',...
      '<br>&nbsp;</font></td></tr>',...
   	'</table></center></div>\n',....
		'&nbsp;<div align="center"><center><table border="1" width="500">\n',...
      '<tr><td><font face="Arial" size="2"><br>',...
	   '&nbsp;&nbsp;&nbsp;&nbsp;Percentile 10: ',num2str(indices(10)),'ms <br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Number of Points: ',num2str(indices(11)),'<br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Maximum: ',num2str(indices(12)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Minimum: ',num2str(indices(13)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Dynamic Range: ',num2str(indices(14)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Dispersion Ratio: ',num2str(indices(15)),'<br><br>\n',...   	'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-1° Quartil: ',num2str(indices(16)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Median: ',num2str(indices(17)),' ms <br>\n',...      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-3° Quartil: ',num2str(indices(18)),' ms <br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Mean: ',num2str(indices(19)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Standard Deviation: ',num2str(indices(20)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Coefficient of Variation: ',num2str(indices(21)),' %%\n',...
   	'<br>&nbsp;</font></td>\n',...
      '<td><font face="Arial" size="2"><br>',...
	   '&nbsp;&nbsp;&nbsp;&nbsp;Percentile 25: ',num2str(indices(22)),'ms <br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Number of Points: ',num2str(indices(23)),'<br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Maximum: ',num2str(indices(24)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Minimum: ',num2str(indices(25)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Dynamic Range: ',num2str(indices(26)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Dispersion Ratio: ',num2str(indices(27)),'<br><br>\n',...   	'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-1° Quartil: ',num2str(indices(28)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Median: ',num2str(indices(29)),' ms <br>\n',...      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-3° Quartil: ',num2str(indices(30)),' ms <br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Mean: ',num2str(indices(31)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Standard Deviation: ',num2str(indices(32)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Coefficient of Variation: ',num2str(indices(33)),' %%\n',...
   	'<br>&nbsp;</font></td></tr>\n',...
      '<tr><td><font face="Arial" size="2"><br>',...
	   '&nbsp;&nbsp;&nbsp;&nbsp;Percentile 50: ',num2str(indices(34)),'ms <br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Number of Points: ',num2str(indices(35)),'<br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Maximum: ',num2str(indices(36)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Minimum: ',num2str(indices(37)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Dynamic Range: ',num2str(indices(38)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Dispersion Ratio: ',num2str(indices(39)),'<br><br>\n',...   	'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-1° Quartil: ',num2str(indices(40)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Median: ',num2str(indices(41)),' ms <br>\n',...      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-3° Quartil: ',num2str(indices(42)),' ms <br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Mean: ',num2str(indices(43)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Standard Deviation: ',num2str(indices(44)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Coefficient of Variation: ',num2str(indices(45)),' %%\n',...
   	'<br>&nbsp;</font></td>\n',...
      '<td><font face="Arial" size="2"><br>',...
	   '&nbsp;&nbsp;&nbsp;&nbsp;Percentile 75: ',num2str(indices(46)),'ms <br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Number of Points: ',num2str(indices(47)),'<br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Maximum: ',num2str(indices(48)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Minimum: ',num2str(indices(49)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Dynamic Range: ',num2str(indices(50)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Dispersion Ratio: ',num2str(indices(51)),'<br><br>\n',...   	'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-1° Quartil: ',num2str(indices(52)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Median: ',num2str(indices(53)),' ms <br>\n',...      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-3° Quartil: ',num2str(indices(54)),' ms <br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Mean: ',num2str(indices(55)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Standard Deviation: ',num2str(indices(56)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Coefficient of Variation: ',num2str(indices(57)),' %%\n',...
      '<br>&nbsp;</font></td></tr>\n',...
      '<tr><td><font face="Arial" size="2"><br>',...
	   '&nbsp;&nbsp;&nbsp;&nbsp;Percentile 90: ',num2str(indices(58)),'ms <br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Number of Points: ',num2str(indices(59)),'<br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Maximum: ',num2str(indices(60)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Minimum: ',num2str(indices(61)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Dynamic Range: ',num2str(indices(62)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Dispersion Ratio: ',num2str(indices(63)),'<br><br>\n',...   	'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-1° Quartil: ',num2str(indices(64)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Median: ',num2str(indices(65)),' ms <br>\n',...      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-3° Quartil: ',num2str(indices(66)),' ms <br><br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Mean: ',num2str(indices(67)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Standard Deviation: ',num2str(indices(68)),' ms <br>\n',...
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-Coefficient of Variation: ',num2str(indices(69)),' %%\n',...
   	'<br>&nbsp;</font></td>\n',...
      '<td><font face="Arial" size="2"><br>',...
   	'<br>&nbsp;</font></td></tr>\n',...      
   	'</table></center></div>'];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Este trecho junta os varios pedacos do arquivo HTML, grava no disco e abre no explorer
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

html_code=[html_header,html_prontuario,html_espectrograma,...
      html_indicesfreq,html_end];

fid = fopen([pathfilename,'.html'],'w');
fprintf(fid,html_code);
fclose(fid);

%cria um arquivo .bat para abrir o explorer
bat_code=[101 99 104 111 32 111 102 102 13 10 99 108 115,...
          13 10 99 58 13 10 99 100 92 97 114 113 117 105,...
          118 126 49 92 105 110 116 101 114 110 126 49,...
          13 10 99 100 92 112 114 111 103 114 97 126 49,...
          92 105 110 116 101 114 110 126 49 13 10 105 101,...
          120 112 108 111 114 101 32 37 49];
fid = fopen([path,'iexplore.bat'],'w');
fwrite(fid,bat_code,'uchar');
fclose(fid);
dos([path,'iexplore.bat ' ,pathfilename,'.html']);

% no matlab 5.3:
% dos([pathfilename,'.html']);