function [tabela_stats,bp_handle]=temporalRR_tabela_stats(intervaloRR,bp_handle,outliers)
% usage: [tabela_stats,bp_handle]=temporalRR_tabela_stats(intervaloRR,bp_handle,outliers);
%
%	string_indices_temporais: uma string formatada com os indices

janela_plotagem_bp=[845 90 165 325]; %[845 160 165 225];

if bp_handle~=-1,
   delete(bp_handle);
end

bp_handle=axes('Units','pixels','Position',janela_plotagem_bp);

if outliers==0,
   temporalRR_boxplot(intervaloRR,0,'x',1,5000)
else
   temporalRR_boxplot(intervaloRR,0,'x',1,1.5)
end   
   
%   BOXPLOT(X,NOTCH,SYM,VERT,WHIS) produces a box and whisker plot for
%   each column of X. The box has lines at the lower quartile, median, 
%   and upper quartile values. The whiskers are lines extending from 
%   each end of the box to show the extent of the rest of the data. 
%   Outliers are data with values beyond the ends of the whiskers.
% 
%   NOTCH = 1 produces a notched-box plot. Notches represent a robust 
%   estimate of the uncertainty about the means for box to box comparison.
%   NOTCH = 0 (default) produces a rectangular box plot. 
%   SYM sets the symbol for the outlier values if any (default='+'). 
%   VERT = 0 makes the boxes horizontal (default: VERT = 1, for vertical).
%   WHIS defines the length of the whiskers as a function of the IQR
%   (default = 1.5). If WHIS = 0 then BOXPLOT displays all data  
%   values outside the box using the plotting symbol, SYM.   

[totaldeamostras,media,mediana,desviopadrao,minimo,maximo,quartil1,...
      quartil3,pnn50,rmssd,coefvar,faixadinamica]=temporalRR_calcula_stats(intervaloRR);

estacionariedade=temporalRR_estacionariedade(intervaloRR);

if estacionariedade(1)>=80,
   yes_no='YES';
else
	yes_no='NO';
end

estacionariedade=[...
      yes_no,'\n       ',...
      num2str(round(estacionariedade(1))) '%% [',...
      num2str(round(estacionariedade(2))) ' ',...
      num2str(round(estacionariedade(3))) ' ',...
      num2str(round(estacionariedade(4))) ' ',...
      num2str(round(estacionariedade(5))) ' ',...
      num2str(round(estacionariedade(6))) ' ',...
      num2str(round(estacionariedade(7))) ']',...
      ];


tabela_stats=sprintf([...
      ' Minimum:           %0.5g ms\n',...
      ' Maximum:           %0.5g ms\n',...
      ' Dynamic Range:     %0.5g ms\n\n',...
      ' 1st Quartile:      %0.5g ms\n',...
      ' Median:            %0.5g ms\n',...
      ' 3rd Quartile:      %0.5g ms\n\n',...
      ' Mean:              %0.5g ms\n',...
      ' Std Deviation:     %0.5g ms\n',...
      ' Coef of Variation: %0.5g %%\n\n',...
      ' pNN50:             %0.5g %%\n',...
      ' r-MSSD:            %0.5g ms\n\n',...
      ' Number of Samples: %0.5g\n\n',...
      ' Stationarity: ',estacionariedade,...
	],...
   minimo,maximo,faixadinamica,quartil1,mediana,quartil3,media,desviopadrao,...
   coefvar,pnn50,rmssd,totaldeamostras);
