%function atfar

%
%
clear,clc %limpa a memoria do matlab

global te_file filename RR tk normais ebs_indices tx_mensagens
global params csastruct handle1 handle2 handle3 eventos prontuario pro_filename fr_prontuario tx_prontlabel pb_edita
global pb_atualiza pb_indices fr_janelas tx_janela1 pu_janela1 tx_janela2 pu_janela2 tx_janela3 pu_janela3
global tx_vlf tx_lf tx_hf tx_hz tx_maxF tx_maxFhz fr_params te_vlf te_lf te_hf te_maxF te_N te_fsAR tx_PSD 
global tx_N tx_fsAR tx_winlen te_winlen tx_wintype pu_wintype tx_fsRR te_fsRR fr_deslocador tx_janela_label
global pb_deslocadir pb_deslocaesq pb_eixoy te_janela_inicio te_janela_fim tx_janela_min tx_janela_max
global fr_eixoy pb_eixoyok te_eixoymin1 te_eixoymax1 te_eixoymin2 te_eixoymax2 te_eixoymin3 te_eixoymax3   
global tx_eixoy1 tx_eixoy2 tx_eixoy3 tx_mensagem pb_eixoyauto1 pb_eixoyauto2 pb_eixoyauto3 cb_rmvect
global rb_AR rb_FFT tx_ordemAR te_ordemAR main_window

%precisa fazer essa chamada para compilar esta funcao
atfar_callbacks(-1);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%estes parametros podem ser facilmente alterados para personalizacao:
%

numerodajanela=100; %numero da figura do MatLab a ser usada como janela principal
fig_largura=1024;fig_altura=702; %largura e altura da janela do programa

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% cria a tela do programa
%
figure(numerodajanela+1);close(numerodajanela+1);
figure(numerodajanela);close(numerodajanela);
main_window=figure(numerodajanela);
clf;
set(main_window,'Name','(GPDS/ENE/UnB) ECGLAB - Time-Frequency Analysis of R-R Intervals',...
   'Position',[1,29,fig_largura,fig_altura],'Color',[.95 .95 .95])

%set(main_window,'Position',[1 -351 fig_largura fig_altura])

mensageminicial=sprintf([...
      'ECGLab - Time-Frequency Analysis Module\n\n\n',...
      'João Luiz Azevedo de Carvalho, Ph.D.\n\n\n',...
      'Digital Signal Processing Group\n',...
      'Department of Electrical Engineering\n',...
      'School of Technology\n',...      
      'University of Brasilia\n\n\n',...
      'joaoluiz@gmail.com',...
]);
tx_mensagem=uicontrol('Style','text','String',mensageminicial,'Position',[100 150 800 500],'FontSize',14,...
   'HorizontalAlignment','center','BackgroundColor',[.95 .95 .95]);   
   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%inicializacao de variaveis
%

fid=fopen('filename.cfg','r');filename=fgetl(fid);fclose(fid); % nome do arquivo a ser aberto
%ponto=find(filename=='.');filename=[filename(1:ponto(length(ponto))-1),'.irr']; %adapta a extensao
RR=-1;
tk=-1;
normais=-1;
ebs_indices=[];
eventos=[];
prontuario='';
pro_filename='';

handle1=-1;handle2=-1;handle3=-1;

opcoes = [...
      'RR Signal               ';...
      'RR Signal (splines)     ';...      
      'Spectrogram             ';...
      'LF/HF Ratio             ';...
      'LF/HF Ratio (areas)     ';...      
      'VLF Power               ';...
      'LF Power                ';...
      'HF Power                ';...
      'Total Power             ';...
      'VLF Power (%)           ';...
      'LF Power (%)            ';...
      'HF Power (%)            ';...
      'Power Spectrum          ';...
      'Wavelet Scalogram       ';...
      'Wavelet Scalogram (log) '];

janelas = [...
      'Rectangular';...
      'Bartlett   ';...
      'Hamming    ';...
      'Hanning    ';...
      'Blackman   '];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: abrir arquivo
%

%frame
fr_abrirarquivo=uicontrol('Style','frame','Position',[20 20 580 60],'BackgroundColor',[1 1 1]);

%texto pedindo o nome do arquivo
tx_file=uicontrol('Style','text',...
   'String','Enter the full path to the IRR or ASCII file to be opened:',...
   'Position',[30 50 300 20],'BackgroundColor',[1 1 1]);

%text edit para entrar com o nome do arquivo
te_file=uicontrol('Style','edit',...
   'String',cd,...
   'Position',[30 30 400 20],'BackgroundColor',[1 1 1],...
	'CallBack','atfar_callbacks(0);');

%botao para abrir o arquivo
pb_abrir_irr=uicontrol('Style','pushbutton',...
   'String','Open IRR',...
   'Position',[440 30 70 30],'BackgroundColor',[1 1 1],...
   'CallBack','atfar_callbacks(1);');
   
%botao para abrir o arquivo
pb_abrir_ascii=uicontrol('Style','pushbutton',...
   'String','Open RR',...
   'Position',[520 30 70 30],'BackgroundColor',[1 1 1],...
   'CallBack','atfar_callbacks(2);');
   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: caixa de mensagens
%
   
%borda em volta da caixa de texto de mensagens 
fr_mensagens=uicontrol('Style','frame','Position',[620 20 390 60],'BackgroundColor',[1 1 1]);
   
%caixa de texto para mensagens
tx_mensagens=uicontrol('Style','text',...
   'Position',[630 30 370 40],'BackgroundColor',[1 1 1],...
   'String', sprintf(['IRR files are the ones obtained from ECGLabRR or EctopicsRR.\nR-R intervals in ASCII must ',...
      'contain a single interval value per line.']));   

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: edicao do prontuario
%

fr_prontuario=uicontrol('Style','frame','Position',[720 100+160 290 40],'Visible','off','BackgroundColor',[1 1 1]);
tx_prontlabel=uicontrol('Style','text','Position',[750-15 110+160 50+10+15 20],'Visible','off','String','Patient Record:','horiz','left','BackgroundColor',[1 1 1]);

pb_edita=uicontrol('Style','pushbutton','Position',[810+10 110+160 80 20],'Visible','off','String','Edit','BackgroundColor',[1 1 1],...
   'CallBack','atfar_callbacks(3);');

pb_atualiza=uicontrol('Style','pushbutton','Position',[900+10 110+160 80 20],'Visible','off','String','Display/Update','BackgroundColor',[1 1 1],...
   'CallBack','atfar_callbacks(4);');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: botao para ver indicies estatisticos
%

pb_indices=uicontrol('Style','pushbutton','Position',[800 160+160 140 40],'BackgroundColor',[1 1 1],'Visible','off',...
   'String','Display Statistics',...
   'CallBack','atfar_callbacks(5)');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: menus para escolher conteudo de cada janela grafica
%
fr_janelas=uicontrol('Style','frame','Position',[720 220+160 290 100],'BackgroundColor',[1 1 1],'Visible','off');

tx_janela1=uicontrol('Style','text','Position',[730 290+160 53 20],'BackgroundColor',[1 1 1],'Visible','off','String','Window 1:','horiz','left');
pu_janela1=uicontrol('Style','popup','Position',[790 290+160 200 20],'BackgroundColor',[1 1 1],'Visible','off','horiz','left','String',opcoes,'Value',1,...
  'CallBack','atfar_callbacks(6);');
 
tx_janela2=uicontrol('Style','text','Position',[730 260+160 53 20],'BackgroundColor',[1 1 1],'Visible','off','String','Window 2:','horiz','left');
pu_janela2=uicontrol('Style','popup','Position',[790 260+160 200 20],'BackgroundColor',[1 1 1],'Visible','off','horiz','left','String',opcoes,'Value',2,...
  'CallBack','atfar_callbacks(7);');

tx_janela3=uicontrol('Style','text','Position',[730 230+160 53 20],'BackgroundColor',[1 1 1],'Visible','off','String','Window 3:','horiz','left');
pu_janela3=uicontrol('Style','popup','Position',[790 230+160 200 20],'BackgroundColor',[1 1 1],'Visible','off','horiz','left','String',opcoes,'Value',3,...
  'CallBack','atfar_callbacks(8);');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%55
%
% GUI: MAXIMA FREQUENCIA MOSTRADA
%
fr_params=uicontrol('Style','frame','Position',[720 340+160 290 350-160],'BackgroundColor',[1 1 1],'Visible','off');

tx_maxF=uicontrol('Style','text','Visible','off',...
   'String','Display frequencies up to:',...
   'Position',[740 350+160 125 20],'BackgroundColor',[1 1 1]);

te_maxF=uicontrol('Style','edit','Visible','off',...
   'String',0,...
   'Position',[865 350+160 40 20],'BackgroundColor',[1 1 1],...
      'Callback','atfar_callbacks(9);');

tx_maxFhz=uicontrol('Style','text','Visible','off','String','Hz','BackgroundColor',[1 1 1],'Position',[905 350+160 20 20]);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: delimitacao das bandas
%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% caixas de texto (label)
%

tx_vlf=uicontrol('Style','text','Visible','off',...
   'String','VLF:',...
   'Position',[740 375+160 30 20],'BackgroundColor',[1 1 1]);

tx_lf=uicontrol('Style','text','Visible','off',...
   'String','Hz    LF:',...
   'Position',[810 375+160 40 20],'BackgroundColor',[1 1 1]);

tx_hf=uicontrol('Style','text','Visible','off',...
   'String','Hz   HF:',...
   'Position',[890 375+160 40 20],'BackgroundColor',[1 1 1]);

tx_hz=uicontrol('Style','text','Visible','off',...
   'String','Hz',...
   'Position',[970 375+160 14 20],'BackgroundColor',[1 1 1]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%55
% caixas de edicao de texto (pontos finais das bandas)
%

te_vlf=uicontrol('Style','edit','Visible','off',...
   'Position',[770 375+160 40 20],'BackgroundColor',[1 1 1],...
   'String',num2str(0),...
   'Callback','atfar_callbacks(10);');

te_lf=uicontrol('Style','edit','Visible','off',...
   'Position',[850 375+160 40 20],'BackgroundColor',[1 1 1],...
   'String',num2str(0),...
   'Callback','atfar_callbacks(11);');

te_hf=uicontrol('Style','edit','Visible','off',...
   'Position',[930 375+160 40 20],'BackgroundColor',[1 1 1],...
   'String',num2str(0),...
   'Callback','atfar_callbacks(12);');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: numero de pontos do PSD
%

tx_PSD=uicontrol('Style','text','Visible','off','String','Spectrogram sampling:','Position',[740 412+160 150 20],'BackgroundColor',[1 1 1]);

te_N=uicontrol('Style','edit','Visible','off',...
   'String','0',...
   'Position',[900 425+160 50 20],'BackgroundColor',[1 1 1],...
   'Callback','atfar_callbacks(13);');

tx_N=uicontrol('Style','text','Visible','off','String','#pts/PSD','Position',[950 425+160 50 20],'BackgroundColor',[1 1 1]);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: amostragem do PSD
%

tx_fsAR=uicontrol('Style','text','Visible','off','String','Hz','Position',[950 400+160 14 20],'BackgroundColor',[1 1 1]);

te_fsAR=uicontrol('Style','edit','Visible','off',...
   'String','0',...
   'Position',[900 400+160 50 20],'BackgroundColor',[1 1 1],...
   'Callback','atfar_callbacks(14);');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: janela do PSD
%

tx_winlen=uicontrol('Style','text','Visible','off','String','Window length:','Position',[725 450+160 75 20],'BackgroundColor',[1 1 1]);

te_winlen=uicontrol('Style','edit','Visible','off',...
   'String','0',...
   'Position',[800 450+160 50 20],'BackgroundColor',[1 1 1],...
   'Callback','atfar_callbacks(15);');

tx_wintype=uicontrol('Style','text','Visible','off','String','seg.       Tipo:','Position',[850 450+160 70 20],'BackgroundColor',[1 1 1]);

pu_wintype=uicontrol('Style','popup','Position',[920 450+160 80 20],'BackgroundColor',[1 1 1],'Visible','off','horiz','left',...
   'String',janelas,'Value',3,'Callback','atfar_callbacks(16);');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: ordem do modelo AR
%

tx_ordemAR=uicontrol('Style','text','Visible','off','String','AR model order:','Position',[740 475+160 110 20],'BackgroundColor',[1 1 1]);

te_ordemAR=uicontrol('Style','edit','Visible','off','BackgroundColor',[1 1 1],...
   'String','0',...
   'Position',[850 475+160 50 20],...
   'Callback','atfar_callbacks(17);');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: taxa de interpolacao do RR
%

tx_fsRR=uicontrol('Style','text','Visible','off','String','RR signal interpolation rate:                    Hz','Position',[740 500+160 205 20],'BackgroundColor',[1 1 1]);

te_fsRR=uicontrol('Style','edit','Visible','off',...
   'String','0',...
   'Position',[880 500+160 50 20],'BackgroundColor',[1 1 1],...
   'Callback','atfar_callbacks(18);');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%55
%
% GUI DESLOCAMENTO DA VISUALIZACAO
% 

%frame do deslocador
fr_deslocador=uicontrol('Style','frame','Position',[720 100 290 140],'BackgroundColor',[1 1 1],'Visible','off');

%label do slider (janela atual)
tx_janela_label=uicontrol('Style','text',...
   'Position',[740 150 240 80],'BackgroundColor',[1 1 1],'HorizontalAlignment','left',...
   'String',sprintf('                        Visualization Window  \n\n\nFrom:                        sec.\n\nTo:                           sec.'),...   
	'Visible','off');
   
%label do minimo do slider
tx_janela_min=uicontrol('Style','text',...
   'Position',[880 170 100 20],'BackgroundColor',[1 1 1],...
   'String','Min=0s',...
   'HorizontalAlignment', 'left',...
	'Visible','off');

%label do maximo do slider
tx_janela_max=uicontrol('Style','text',...
   'Position',[880 150 100 20],'BackgroundColor',[1 1 1],...
   'String','Max=0s',...
   'HorizontalAlignment', 'left',...
   'Visible','off');
   
%text edit que mostra/modifica a posicao da janela atual
te_janela_inicio=uicontrol('Style','edit',...
   'Position',[773 175 60 20],'BackgroundColor',[1 1 1],...
   'String','0',...
   'Visible','off',...
   'CallBack','atfar_callbacks(19);');

%text edit para determinar o tamanho da janela de deslocamento
te_janela_fim=uicontrol('Style','edit',...
   'Position',[773 150 60 20],'BackgroundColor',[1 1 1],...
	'String','0',...
   'Visible','off',...
   'CallBack','atfar_callbacks(20);');

%botao que desloca uma janela para esquerda
pb_deslocaesq=uicontrol('Style','pushbutton',...
   'String','<',...
	'Position',[773 120 20 20],'BackgroundColor',[1 1 1],...
   'Visible','off',...
   'Callback','atfar_callbacks(21);');



%botao que desloca uma janela para direita
pb_deslocadir=uicontrol('Style','pushbutton',...
   'String','>',...
	'Position',[813 120 20 20],'BackgroundColor',[1 1 1],...
   'Visible','off',...
   'Callback','atfar_callbacks(22);');   


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: ajuste do eixo das amplitudes (eixoy)
%

pb_eixoy=uicontrol('Style','pushbutton',...
   'Position',[880 115 100 30], 'BackgroundColor',[1 1 1],...
   'String','Adjust Y-Axis','Visible','off','CallBack','atfar_callbacks(23);');   
   
fr_eixoy=uicontrol('Style','frame','Position',[720 100 290 140],'BackgroundColor',[1 1 1],'Visible','off');
   
pb_eixoyok=uicontrol('Style','pushbutton',...
   'Position',[880 115 100 30], 'BackgroundColor',[1 1 1],...
   'String','Back','Visible','off','CallBack','atfar_callbacks(24);');   

tx_eixoy1=uicontrol('Style','text',...
   'Position',[730 210 180 20],'BackgroundColor',[1 1 1],...
	'String','Plot 1:                                to','HorizontalAlignment','left',...
   'Visible','off');

te_eixoymin1=uicontrol('Style','edit',...
   'Position',[790 210 60 20],'BackgroundColor',[1 1 1],...
	'String','0',...
   'Visible','off',...
   'Callback','atfar_callbacks(25);');   
   
te_eixoymax1=uicontrol('Style','edit',...
   'Position',[870 210 60 20],'BackgroundColor',[1 1 1],...
	'String','0',...
   'Visible','off',...
   'Callback','atfar_callbacks(26);');   
   
tx_eixoy2=uicontrol('Style','text',...
   'Position',[730 180 180 20],'BackgroundColor',[1 1 1],...
	'String','Plot 2:                                to','HorizontalAlignment','left',...
   'Visible','off');

te_eixoymin2=uicontrol('Style','edit',...
   'Position',[790 180 60 20],'BackgroundColor',[1 1 1],...
	'String','0',...
   'Visible','off',...
   'Callback','atfar_callbacks(27);');   
   
te_eixoymax2=uicontrol('Style','edit',...
   'Position',[870 180 60 20],'BackgroundColor',[1 1 1],...
	'String','0',...
   'Visible','off',...
   'Callback','atfar_callbacks(28);');   
   
tx_eixoy3=uicontrol('Style','text',...
   'Position',[730 150 180 20],'BackgroundColor',[1 1 1],...
	'String','Plot 3:                                to','HorizontalAlignment','left',...
   'Visible','off');

te_eixoymin3=uicontrol('Style','edit',...
   'Position',[790 150 60 20],'BackgroundColor',[1 1 1],...
	'String','0',...
   'Visible','off',...
   'Callback','atfar_callbacks(29);');   
   
te_eixoymax3=uicontrol('Style','edit',...
   'Position',[870 150 60 20],'BackgroundColor',[1 1 1],...
	'String','0',...
   'Visible','off',...
   'Callback','atfar_callbacks(30);');   
   
pb_eixoyauto1=uicontrol('Style','pushbutton',...
   'Position',[940 210 60 20],'BackgroundColor',[1 1 1],...
	'String','Auto',...
   'Visible','off',...
   'Callback','atfar_callbacks(31);');   
   
pb_eixoyauto2=uicontrol('Style','pushbutton',...
   'Position',[940 180 60 20],'BackgroundColor',[1 1 1],...
	'String','Auto',...
   'Visible','off',...
   'Callback','atfar_callbacks(32);');   
   
pb_eixoyauto3=uicontrol('Style','pushbutton',...
   'Position',[940 150 60 20],'BackgroundColor',[1 1 1],...
	'String','Auto',...
   'Visible','off',...
   'Callback','atfar_callbacks(33);');
   
   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: remover ectopicos
%

cb_rmvect=uicontrol('Style','checkbox','Visible','off','String','Ectopic',...
   'Position',[940 510 68 20],'BackgroundColor',[1 1 1],...
   'CallBack','atfar_callbacks(34);');
   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: AR ou Fourier
%

rb_AR=uicontrol('Style','radio','Visible','off','String','AR',...
   'Position',[955 660 40 20],'BackgroundColor',[1 1 1],...
   'CallBack','atfar_callbacks(35);');

rb_FFT=uicontrol('Style','radio','Visible','off','String','Fourier',...
   'Position',[955 635 53 20],'BackgroundColor',[1 1 1],...
   'CallBack','atfar_callbacks(36);');
   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%