% PARA INSTRUCOES SOBRE USO, LEIA O ARQUIVO SEQUENCIALRR_README.DOC
%
%
clear %limpa a memoria do matlab

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%estes parametros podem ser facilmente alterados para personalizacao:
%

numerodajanela=100; %numero da figura do MatLab a ser usada como janela principal
fig_largura=1024;fig_altura=702; %largura e altura da janela do programa

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% cria a tela do programa
%
figure(numerodajanela+1);close(numerodajanela+1);
figure(numerodajanela);close(numerodajanela);
main_window=figure(numerodajanela);
clf;
set(main_window,'Name','(GPDS/ENE/UnB) ECGLAB - Sequential Trend Analysis','Position',[1,29,fig_largura,fig_altura])

mensageminicial=sprintf([...
      'ECGLAB - Sequential Trend Analysis of R-R Intervals\n\n\n',...
      'João Luiz Azevedo de Carvalho, Ph.D.\n\n\n',...
      'Digital Signal Processing Group\n',...
      'Department of Electrical Engineering\n',...
      'School of Technology\n',...      
      'University of Brasilia\n\n\n',...
      'joaoluiz@gmail.com',...
]);      
tx_mensagem=uicontrol('Style','text','String',mensageminicial,'Position',[100 150 800 500],'FontSize',14,...
   'HorizontalAlignment','center','BackgroundColor',[.8 .8 .8]);   

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%inicializacao de variaveis
%
fid=fopen('filename.cfg','r');filename=fgetl(fid);fclose(fid); % nome do arquivo a ser aberto
ponto=find(filename=='.');filename=[filename(1:ponto(length(ponto))-1),'.irr']; %adapta a extensao
eventos=[];
intervaloRR=-1;
tempoRR=-1;
intervaloRR_original=-1;
tempoRR_original=-1;
verdadeiros=-1;
ebs_indices=[];
handle=-1;
prontuario='';
pro_filename='';
eixo=-1;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: abrir arquivo
%

%frame
fr_abrirarquivo=uicontrol('Style','frame','Position',[80 20 580 60]);

%texto pedindo o nome do arquivo
tx_file=uicontrol('Style','text',...
   'String','Enter the full path to the IRR or ASCII file to be opened:',...
   'Position',[90 50 300 20]);

%text edit para entrar com o nome do arquivo
te_file=uicontrol('Style','edit',...
   'String',filename,...
   'Position',[90 30 400 20],...
	'CallBack',[...
      'filename=get(te_file,''String'');',...
      'set(te_file,''String'',filename);',...
		'fid=fopen(''filename.cfg'',''w'');fwrite(fid,filename,''char'');fclose(fid);',...
	]);

%botao para abrir o arquivo
pb_abrir_irr=uicontrol('Style','pushbutton',...
   'String','Open IRR',...
   'Position',[500 30 70 30],...
   'CallBack',	[...
      'filename=get(te_file,''String'');',...
      '[intervaloRR,tempoRR,verdadeiros,ebs_indices]=le_IRR(filename);',...
      'intervaloRR_original=intervaloRR;tempoRR_original=tempoRR;',...
		'if intervaloRR(1)~=-1,',...
          'set(tx_mensagem,''Visible'',''off'');',...
  	      '[intervaloRR,tempoRR]=temporalRR_interpola(intervaloRR_original,tempoRR_original,ebs_indices);',...
   		'eixo=sequencialRR_le_cfg(filename,intervaloRR);',...
			'sequencialRR_salva_cfg(filename,eixo);',...
         '[handle,indices]=sequencialRR_grafico(intervaloRR,eixo,handle);',...
      	'tabela=sequencialRR_tabela(indices);',...
      	'set(tx_stats,''String'',tabela);',...
   		'set(tx_mensagens, ''String'', '' '');',...
   		'eventos=le_eventos(filename);',...
         '[prontuario,pro_filename]=le_prontuario(filename,eventos);',...
      	'set(fr_tabelarr,''Visible'',''on'');',...
      	'set(pb_versinal,''Visible'',''on'');',...
      	'set(fr_prontuario,''Visible'',''on'');',...
			'set(tx_prontlabel,''Visible'',''on'');',...
			'set(pb_edita,''Visible'',''on'');',...
         'set(pb_atualiza,''Visible'',''on'');',...
			'set(fr_ectopics,''Visible'',''on'');',...
			'set(tx_eblabel,''Visible'',''on'');',...
			'set(rb_remove,''Visible'',''on'',''Value'',0);',...
			'set(rb_interpola,''Visible'',''on'',''Value'',1);',...
         'set(rb_naoremove,''Visible'',''on'',''Value'',0);',...
	      'set(fr_controles,''Visible'',''on'');',...
   	   'set(tx_labelx1,''Visible'',''on'');',...
      	'set(te_eixox1,''Visible'',''on'',''String'',num2str(eixo));',...
	      'set(tx_labelx2,''Visible'',''on'');',...
      	'set(pb_html,''Visible'',''on'');',...
			'set(pb_tabelarr,''Visible'',''on'');',...
			'set(pb_print,''Visible'',''on'');',...
			'set(tx_stats,''Visible'',''on'');',...
         'set(fr_stats,''Visible'',''on'');',...   
         'set(tx_rr,''Visible'',''on'');',...            
      'else,',...
          'set(tx_mensagem,''Visible'',''on'');',...
	      'set(tx_mensagens, ''String'', ''This file does not contain R-R intervals!'');',...
         'eventos=[];pro_filename=[];prontuario=[];',...
         'if handle~=-1, delete(handle);handle=-1;end,',...
      	'set(fr_prontuario,''Visible'',''off'');',...
			'set(tx_prontlabel,''Visible'',''off'');',...
			'set(pb_edita,''Visible'',''off'');',...
         'set(pb_atualiza,''Visible'',''off'');',...
			'set(fr_ectopics,''Visible'',''off'');',...
			'set(tx_eblabel,''Visible'',''off'');',...
			'set(rb_remove,''Visible'',''off'');',...
			'set(rb_interpola,''Visible'',''off'');',...
         'set(rb_naoremove,''Visible'',''off'');',...
	      'set(fr_controles,''Visible'',''off'');',...
   	   'set(tx_labelx1,''Visible'',''off'');',...
      	'set(te_eixox1,''Visible'',''off'');',...
	      'set(tx_labelx2,''Visible'',''off'');',...
         'set(pb_html,''Visible'',''off'');',...
			'set(pb_tabelarr,''Visible'',''off'');',...
			'set(pb_print,''Visible'',''off'');',...
			'set(tx_stats,''Visible'',''off'');',...
         'set(fr_stats,''Visible'',''off'');',...   
      	'set(fr_tabelarr,''Visible'',''off'');',...
         'set(pb_versinal,''Visible'',''off'');',...
         'set(tx_rr,''Visible'',''off'');',...                     
      'end,',...
		]);
   
%botao para abrir o arquivo
pb_abrir_ascii=uicontrol('Style','pushbutton',...
   'String','Open ASCII',...
   'Position',[580 30 70 30],...
   'CallBack',	[...
      'filename=get(te_file,''String'');',...
      '[intervaloRR,tempoRR,verdadeiros,ebs_indices]=le_IRR_ascii(filename);',...
      'intervaloRR_original=intervaloRR;tempoRR_original=tempoRR;',...
		'if intervaloRR(1)~=-1,',...
          'set(tx_mensagem,''Visible'',''off'');',...
  	      '[intervaloRR,tempoRR]=temporalRR_interpola(intervaloRR_original,tempoRR_original,ebs_indices);',...
   		'eixo=sequencialRR_le_cfg(filename,intervaloRR);',...
         'sequencialRR_salva_cfg(filename,eixo);',...
         '[handle,indices]=sequencialRR_grafico(intervaloRR,eixo,handle);',...
      	'tabela=sequencialRR_tabela(indices);',...
	     	'set(tx_stats,''String'',tabela);',...
   		'set(tx_mensagens, ''String'', '' '');',...
   		'eventos=[];',...
         '[prontuario,pro_filename]=le_prontuario(filename,eventos);',...
      	'set(fr_prontuario,''Visible'',''on'');',...
			'set(tx_prontlabel,''Visible'',''on'');',...
			'set(pb_edita,''Visible'',''on'');',...
         'set(pb_atualiza,''Visible'',''on'');',...
			'set(fr_ectopics,''Visible'',''off'');',...
			'set(tx_eblabel,''Visible'',''off'');',...
			'set(rb_remove,''Visible'',''off'',''Value'',0);',...
			'set(rb_interpola,''Visible'',''off'',''Value'',1);',...
         'set(rb_naoremove,''Visible'',''off'',''Value'',0);',...
	      'set(fr_controles,''Visible'',''on'');',...
   	   'set(tx_labelx1,''Visible'',''on'');',...
      	'set(te_eixox1,''Visible'',''on'',''String'',num2str(eixo));',...
	      'set(tx_labelx2,''Visible'',''on'');',...
         'set(pb_html,''Visible'',''on'');',...
			'set(pb_tabelarr,''Visible'',''on'');',...
			'set(pb_print,''Visible'',''on'');',...
			'set(tx_stats,''Visible'',''on'');',...
         'set(fr_stats,''Visible'',''on'');',...   
      	'set(fr_tabelarr,''Visible'',''on'');',...
         'set(pb_versinal,''Visible'',''on'');',...
         'set(tx_rr,''Visible'',''on'');',...                     
      'else,',...
        'set(tx_mensagem,''Visible'',''on'');',...
      	'set(tx_mensagens, ''String'', ''This file does not contain R-R intervals! ',...
      		'Each line must contain only 1 interval value!'');',...
         'eventos=[];pro_filename=[];prontuario=[];',...
			'set(fr_prontuario,''Visible'',''off'');',...
			'set(tx_prontlabel,''Visible'',''off'');',...
         'if handle~=-1, delete(handle);handle=-1;end,',...
      	'set(pb_edita,''Visible'',''off'');',...
         'set(pb_atualiza,''Visible'',''off'');',...
			'set(fr_ectopics,''Visible'',''off'');',...
			'set(tx_eblabel,''Visible'',''off'');',...
			'set(rb_remove,''Visible'',''off'');',...
			'set(rb_interpola,''Visible'',''off'');',...
			'set(rb_naoremove,''Visible'',''off'');',...
	      'set(fr_controles,''Visible'',''off'');',...
   	   'set(tx_labelx1,''Visible'',''off'');',...
      	'set(te_eixox1,''Visible'',''off'');',...
	      'set(tx_labelx2,''Visible'',''off'');',...
         'set(pb_html,''Visible'',''off'');',...
			'set(pb_tabelarr,''Visible'',''off'');',...
			'set(pb_print,''Visible'',''off'');',...
			'set(tx_stats,''Visible'',''off'');',...
         'set(fr_stats,''Visible'',''off'');',...   
      	'set(fr_tabelarr,''Visible'',''off'');',...
         'set(pb_versinal,''Visible'',''off'');',...
         'set(tx_rr,''Visible'',''off'');',...                     
      'end,',...
		]);
   
   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: caixa de mensagens
%
   
%borda em volta da caixa de texto de mensagens 
fr_mensagens=uicontrol('Style','frame','Position',[680 20 300 60]);
   
%caixa de texto para mensagens
tx_mensagens=uicontrol('Style','text',...
   'Position',[690 30 280 40],...
   'String', ['IRR files are the ones obtained from ECGLabRR or EctopicsRR. R-R intervals in ASCII must ',...
      'contain a single interval value per line.']);   

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: edicao do prontuario
%

fr_prontuario=uicontrol('Style','frame','Position',[680 90 170 60],'Visible','off');
tx_prontlabel=uicontrol('Style','text','Position',[690 120 150 20],'Visible','off','String','Patient Record','horiz','cent');

pb_edita=uicontrol('Style','pushbutton','Position',[690 100 70 20],'Visible','off','String','Edit',...
   'CallBack',[...
   	'dos([''write '',pro_filename]);',...
      'set(tx_mensagens,''String'',''When you are done editing the patient''''s record on Wordpad, ',...
      'please save the file and click on VIEW/UPDATE.'');',...
	]);

pb_atualiza=uicontrol('Style','pushbutton','Position',[770 100 70 20],'Visible','off','String','View/Update',...
   'CallBack',[...
      'prontuario=le_prontuario(pro_filename,eventos);',...
      'mostrar_prontuario(prontuario);',...
      'set(tx_mensagens,''String'','''');',...
      ]);
   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: remocao/interpolacao de batimentos ectopicos
%

fr_ectopics=uicontrol('Style','frame','Position',[820-60 320 190 100],'Visible','off');
tx_eblabel=uicontrol('Style','text','Position',[850-60 390 140 20],'Visible','off','String','Ectopic Beats:','horiz','left');

rb_remove=uicontrol('Style','radio','Position',[850-60 370 140 20],'Visible','off','String','Remove','Value',0,...
   'CallBack',[...
      'set(rb_remove   ,''Value'',1);',...
      'set(rb_interpola,''Value'',0);',...
      'set(rb_naoremove,''Value'',0);',...
      'tempoRR=tempoRR_original(verdadeiros);',...
      'intervaloRR=intervaloRR_original(verdadeiros);',...
      '[handle,indices]=sequencialRR_grafico(intervaloRR,eixo,handle);',...
   	'tabela=sequencialRR_tabela(indices);',...
     	'set(tx_stats,''String'',tabela);',...
	]);

rb_interpola=uicontrol('Style','radio','Position',[850-60 350 140 20],'Visible','off','String','Remove & Interpolate','Value',1,...
   'CallBack',[...
      'set(rb_remove   ,''Value'',0);',...
      'set(rb_interpola,''Value'',1);',...
      'set(rb_naoremove,''Value'',0);',...
      '[intervaloRR,tempoRR]=temporalRR_interpola(intervaloRR_original,tempoRR_original,ebs_indices);',...
      '[handle,indices]=sequencialRR_grafico(intervaloRR,eixo,handle);',...
    	'tabela=sequencialRR_tabela(indices);',...
     	'set(tx_stats,''String'',tabela);',...
   ]);

rb_naoremove=uicontrol('Style','radio','Position',[850-60 330 140 20],'Visible','off','String','Don''t Remove','Value',0,...
   'CallBack',[...
      'set(rb_remove   ,''Value'',0);',...
      'set(rb_interpola,''Value'',0);',...
      'set(rb_naoremove,''Value'',1);',...
      'tempoRR=tempoRR_original;',...
      'intervaloRR=intervaloRR_original;',...
      '[handle,indices]=sequencialRR_grafico(intervaloRR,eixo,handle);',...
	   'tabela=sequencialRR_tabela(indices);',...
     	'set(tx_stats,''String'',tabela);',...
   ]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: limites do grafico
%

fr_controles=uicontrol('Visible','off','Style','frame','Position',[820-60 430 190 40]);

% caixas de texto (label)
tx_labelx1=uicontrol('Visible','off','Style','text',...
   'String','Plot Limits:',...
   'Position',[830-60 440 80 20]);

% caixas de edicao de texto (pontos finais do grafico)
te_eixox1=uicontrol('Visible','off','Style','edit',...
   'Position',[910-60 440 60 20],...
   'Value', eixo,...
	'String',num2str(eixo),...
   'Callback',[...
      'A=str2num(get(te_eixox1,''String''));',...
      'if length(A)==1,',...
	   	'if A >0,',...
         	'eixo=floor(A);',... %tira as casas decimais
	      'end,',...
   	'end,',...
       '[handle,indices]=sequencialRR_grafico(intervaloRR,eixo,handle);',...
      'set(te_eixox1,''String'',num2str(eixo));',...
      'sequencialRR_salva_cfg(filename,eixo);',...
	]);

% caixas de texto (label)
tx_labelx2=uicontrol('Visible','off','Style','text',...
   'String','ms',...
   'Position',[970-60 440 20 20]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: estatistica
%

fr_stats=uicontrol('Style','frame','Position',[740   480   230   215],'Visible','off');
tx_stats=uicontrol('Style','text','Position',[755   490   214   190],...
   'Visible','off','Hor','left','Fontname','Terminal','FontSize',6);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: gera html
%

pb_html=uicontrol('Style','push','Position',[860 100 120 40],'Visible','off',...
   'String','HTML Report','CallBack',[...
	'sequencialRR_gera_html(filename,prontuario,intervaloRR,eixo);',...      
	]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% GUI: tabela dos R-R
%

fr_tabelarr=uicontrol('Style','frame','Position',[820-60 160 190 150],'Visible','off');

tx_rr=uicontrol('Style','text','visible','off','string','R-R Intervals','hor','cent','position',[821-60 280 188 20]);

pb_versinal=uicontrol('Style','push','Position',[845-60 250 140 30],'Visible','off',...
   'String','Display R-R Signal','CallBack',[...
      'temporalRR_intervalograma2(tempoRR,intervaloRR,eventos,''evnt'','...
      	'min(tempoRR(find(tempoRR>0))),max(tempoRR),min(intervaloRR)-25,max(intervaloRR)+25);',...      
   ]);

pb_tabelarr=uicontrol('Style','push','Position',[845-60 210 140 30],'Visible','off',...
   'String','Table of R-R Intervals','CallBack',[...
	'temporalRR_tabelaRR(intervaloRR);',...      
	]);

pb_print=uicontrol('Style','push','Position',[845-60 170 140 30],'Visible','off',...
   'String','Print R-R Intervals','CallBack',[...
  	'dos([''write '',salva_irr_txt(intervaloRR,[],filename)]);',...      
	]);


